### PR TITLE
Add `setPublicDataForUser()` — useful for updating the role of another user

### PR DESCRIPTION
**Pull request by lksnmnn**
Closes: https://github.com/blitz-js/blitz/issues/2449
Documentation PR: https://github.com/blitz-js/blitzjs.com/pull/500

### What are the changes and their implications?

This change adds a new API to update a user's `publicData` across all of the user's active sessions. Among other things this feature solves the common usecase, where a user's role is changed and the change should be reflected immediatly, i.e., when the user is denoted from "admin" to "user".

## Bug Checklist

- [x] Integration test added (see [test docs](https://blitzjs.com/docs/contributing#running-tests) if needed)

## Feature Checklist

- [x] Integration test added (see [test docs](https://blitzjs.com/docs/contributing#running-tests) if needed)
- [x] Documentation added/updated (submit PR to [blitzjs.com repo](https://github.com/blitz-js/blitzjs.com))

### CODE REVIEW

**Review by flybayer — APPROVED** [review]
Thank you!!

**Comment by lksnmnn** [comment]
There is one thing I might want to test with this, that is actually being logged in with both users and check what happens to the user, when his publiData is being updated.

In my version of this function, which I posted in the linked issue, it worked, but when I changed browsers to quickly after updating the role, the user got weird invalid session and CSRF errors. Which is probably a bug in the session logic, but using this new API could trigger this.

**Comment by flybayer** [comment]
@lksnmnn ok good to know. You are going to test?

**Comment by lksnmnn** [comment]
I could not reproduce this bug in the auth example. So I guess the issue was my code doing something weird. 🚀

**Comment by flybayer** [comment]
Ok thank you, we'll roll with this and address the bug later if it shows up

**Pull request merged**
