### PR TITLE
Add README for tailwind CSS recipe

### PR DESCRIPTION
**Pull request by kimngan-bui**
Issue #2403 

### What are the changes and their implications?
Added Tailwind CSS's README for it's blitz recipe

## Bug Checklist

- [ ] Integration test added (see [test docs](https://blitzjs.com/docs/contributing#running-tests) if needed)

## Feature Checklist

- [ ] Integration test added (see [test docs](https://blitzjs.com/docs/contributing#running-tests) if needed)
- [ ] Documentation added/updated (submit PR to [blitzjs.com repo](https://github.com/blitz-js/blitzjs.com))

### CODE REVIEW

**Comment by beerose** [comment]
Hey! Thanks for your contributions. Would you mind combining your PRs into a single one (since they tackle the same issue)?

**Comment by kimngan-bui** [comment]
> Hey! Thanks for your contributions. Would you mind combining your PRs into a single one (since they tackle the same issue)?

Hi, how do I do that? I was just following the example set by the others, e.g. @johnmurphy01

**Comment by beerose** [comment]
You can close your other PRs and add the remaining Readmes in this PR :)

**Comment by kimngan-bui** [comment]
> You can close your other PRs and add the remaining Readmes in this PR :)

They were all made on different branches, how would that work? Wouldn't it be easier to just merge them in? I'm starting to feel a bit singled out here.. and I'm not sure I see the added value of the proposed changes. Sorry if that doesn't make sense.

**Comment by beerose** [comment]
I was thinking that we can have one commit in git history with `add recipes for ..., and ...`, but it's okay, I'll just go ahead and merge them as they are :)

**Pull request merged**
