### PR TITLE
Update log.ts

### PR DESCRIPTION
**Pull request by nabi009**
### Type: ?? 

Closes: ??

### What are the changes and their implications? :gear:

??

### Checklist

- [x] Tests added for changes
- [x] Any added terminal logging uses `packages/server/src/log.ts`

### CODE REVIEW

**Comment by flybayer** [comment]
Hey @nabi009, thank you for your contribution!

It looks like you `log.pointing` isn't being used anywhere. Did you intend to log something with it?

**Comment by nabi009** [comment]
@flybayer, I removed it for now.

**Comment by flybayer** [comment]
@nabi009 CI is failing for this. Can you look into it?

**Comment by nabi009** [comment]
`const withPointing = (str: string) => {
   return `👉  ${chalk.yellow(str)}`
 }`

it is just returning icon with string. what will be the error, anyhow I will check it. thanks

**Comment by merelinguist** [comment]
Is `withPointing` used anywhere?

**Comment by nabi009** [comment]
> Is `withPointing` used anywhere?

Yes in cli/command/db.ts

**Comment by ryardley** [comment]
> Yes in cli/command/db.ts #383

Does it make sense to perhaps simply include it with that work?

**Comment by nabi009** [comment]
> > Yes in cli/command/db.ts #383
> 
> 
> 
> Does it make sense to perhaps simply include it with that work?

It pointing commands to users that you can use these specific comments.

**Comment by ryardley** [comment]
> Does it make sense to perhaps simply include it with that work?

What I mean is that I think we should merge this change into https://github.com/blitz-js/blitz/pull/408 as they depend on each other.

**Comment by flybayer** [comment]
Closing — see https://github.com/blitz-js/blitz/pull/408#issuecomment-632130242

**Pull request closed without merging**
