### PR TITLE
(meta) fix ultra scripts so they work on Windows

### PR DESCRIPTION
**Pull request by wKovacs64**
Closes: N/A

### What are the changes and their implications?

Single quotes in package.json scripts don't work in Windows like you'd expect. Because... Windows. This just replaces them with escaped double quotes.

### Checklist

- [ ] Changes covered by tests (tests added if needed)
- [ ] Does this PR warrant documentation updates? If yes, open a second PR with doc changes to [blitzjs.com](https://github.com/blitz-js/blitzjs.com)

### CODE REVIEW

**Comment by wKovacs64** [comment]
The irony of this change only failing on the Windows image in CI is palpable.

**Comment by flybayer** [comment]
lol, looks like it failed on both. Do you know why?

**Comment by wKovacs64** [comment]
Yeah, flaky CI afaict. It only failed on Windows the first time, then when I re-ran the jobs it failed on others, too. 🤷‍♂️

**Comment by flybayer** [comment]
I'm confused because other PRs are not having this test failure 🤔

**Comment by wKovacs64** [comment]
I'm a bit perplexed by it as well, especially since it's just changing quotes and those commands are obviously still executing. Although another PR that was just merged was passing pre-merge and failed post-merge (on a different test, though) so I'm not sure how confident I am in CI at the moment. 🤷‍♂️

**Pull request merged**
