### PR TITLE
fix(examples): Fix Yarn link blitz cli failing

### LINKED ISSUE #101: Yarn link for Blitz CLI is failing on db migrate
1. `cd packages/cli`
2. `yarn link`
3. `cd ../../examples/store`
4. `blitz db migrate`

Fails with:
```
~/c/b/e/store> blitz db migrate
Error: spawn prisma ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

### PR DESCRIPTION
**Pull request by ryardley**
Closes #101  

So for yarn workspaces dependencies to install properly it looks like you need package version.

### CODE REVIEW

**Comment by flybayer** [comment]
Still failing for me. Also, I'm pretty sure lerna stuff is not the issue here. The issues is the CLI, not the dependency linking.

**Comment by ryardley** [comment]
This was definitely the missing link. 

It will not work until you do a yarn install and a `yarn build`.

**Comment by ryardley** [comment]
I can confirm I have double checked and If you do the above steps with canary you will get:

```
➜ blitz db migrate
Error: spawn prisma ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by merelinguist** [comment]
Changing the versions fixed it for me.

**Pull request merged**
