### PR TITLE
Use previous build for `blitz start --production` if up-to-date

### PR DESCRIPTION
**Pull request by ryardley**
Closes: #540

### Checklist

- [x] Tests added for changes
- [x] User facing changes documented

### Other information

- [x] Build is not happening when files are the same
- [x] Add testing

### CODE REVIEW

**Comment by merelinguist** [comment]
Is [this](https://github.com/blitz-js/blitz/issues/226) within the pr scope?

**Comment by ryardley** [comment]
> Is [this](https://github.com/blitz-js/blitz/issues/226) within the pr scope?

No it isn't. That is a different problem. 

This assumes builds are either complete or not. #226 is checking for partial builds and optimizing accordingly and was more valuable optimizing against large codebases.

**Comment by ryardley** [comment]
So after having done this I am wondering perhaps the checksumming logic should occur within the build function itself? That means that running build twice without changing input will not do anything. Thoughts?

**Comment by flybayer** [comment]
@ryardley we could, but I'm not sure the UX is great. Like, if you run `blitz build` you expect it to build something, but if instead it says, already built, no changes, then you may not trust the system and want a `--force` flag. 🤷

**Pull request merged**
