### PR TITLE
chore: make 'blitz' work

### LINKED ISSUE #126: [Help Wanted!] Make CLI work from the `blitz` package and with npx
We need the following:

- [x] Be able to install the blitz cli globally with yarn/npm from the `blitz` package instead of `@blitzjs/cli`
- [x] `npx blitz --help` to work
- [x] The globally installed binary delegates to the locally installed version in the app. So `blitz start` in an app will use the blitz version in package.json.

This is needed for our imminent alpha release, so I'd love if someone can jump on this!

### PR DESCRIPTION
**Pull request by medelman17**
Fixes issues in #128 

It should also close #126, but we'll need to make sure we cover all the required/expected use cases.

### CODE REVIEW

**Comment by flybayer** [comment]
@medelman17 thank you! Totally makes senses to not use tsdx for the blitz package.

So I'm still having issues (I ran git clean for a fresh repo state)

`yarn dev` from repo root errors:

```
~/c/blitz> yarn dev
yarn run v1.22.4
$ lerna run start --scope blitz --scope @blitzjs/* --stream --parallel
lerna notice cli v3.20.2
lerna notice filter including ["blitz","@blitzjs/*"]
lerna info filter [ 'blitz', '@blitzjs/*' ]
lerna info Executing command in 3 packages: "yarn run start"
@blitzjs/server: $ tsdx watch
@blitzjs/core: $ tsdx watch
blitz: $ yarn dev
blitz: $ rollup -c rollup.config.js --watch
@blitzjs/core: -
@blitzjs/server: -
blitz: rollup v2.6.1
blitz: bundles ./src/index.ts → dist/index.js...
@blitzjs/core: - Compiling modules...
@blitzjs/server: - Compiling modules...
blitz: [!] (plugin Typescript) TS7016: Could not find a declaration file for module '@blitzjs/core'. '/Users/b/c/blitz/packages/core/dist/index.js' implicitly has an 'any' type.
blitz:   Try `npm install @types/blitzjs__core` if it exists or add a new declaration (.d.ts) file containing `declare module '@blitzjs/core';`
blitz: src/index.ts (1:15)
blitz: 1 export * from '@blitzjs/core'
```

**Comment by flybayer** [comment]
`yarn build` does build everything properly.

But then `yarn blitz start` inside `examples/store` fails:

```
~/c/b/e/store> y blitz start
yarn run v1.22.4
$ /Users/b/c/blitz/node_modules/.bin/blitz start
BlitzJS/CLI found locally (hoisted)...using that
[ wait ]  starting the development server ...
[ info ]  waiting on http://localhost:3000 ...
> Info: Loaded env from .env
/Users/b/c/blitz/packages/blitz/dist/index.js:1
export * from '@blitzjs/core';
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1072:16)
    at Module._compile (internal/modules/cjs/loader.js:1122:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/b/c/blitz/examples/store/.blitz/caches/dev/next.config.js:1:21)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
```

**Comment by flybayer** [comment]
Using blitz globally after doing `yarn link` from `packages/blitz` results in this:

```
/p/tmp> blitz
BlitzJS/CLI not found locally; trying global...
BlitzJS/CLI not found locally; trying global...
BlitzJS/CLI not found locally; trying global...
BlitzJS/CLI not found locally; trying global...
BlitzJS/CLI not found locally; trying global...
BlitzJS/CLI not found locally; trying global...
```

**Comment by flybayer** [comment]
Global usage via yarn link is a special case. I think it need's its own detection logic.

**Comment by medelman17** [comment]
@flybayer: the `store` example spins up correctly as far as the CLI is concerned (I think)... but errors out re: `@blitz/server` not being able to find `child_process`. I can't think of anything that I might have done here that would cause that error. And the `blitz` package seems to work fine in the deprecated `vanilla` example.

**Pull request merged**
