### PR TITLE
Initialize git before app generate to properly set up husky hooks

### PR DESCRIPTION
**Pull request by peaonunes**
### Type: bug fix
Closes: #330

### What are the changes and their implications? :gear:
* Git init happens before any other step in `AppGenerator`.
* Husky hooks will now correctly be applied when commiting files.

### Checklist
- [x] Tests added for changes
- [ ] Any added terminal logging uses `packages/server/src/log.ts`

### CODE REVIEW

**Comment by flybayer** [comment]
LGTM 🚀

**Comment by peaonunes** [comment]
Hey @aem just rebased with your latest refactor of moving `generators` away from the `cli`.
Should be good to go now 😄

**Comment by aem** [comment]
@peaonunes thanks! sorry about moving all the files out from under you, I forgot this was open 😞

**Comment by peaonunes** [comment]
No worries! I'm glad that I could help @aem .

**Pull request merged**
