### PR TITLE
update prisma-ast version in blitz generator package

### PR DESCRIPTION
**Pull request by isurumaldeniya**
Closes: #3190 

### What are the changes and their implications?
Updated the **`prisma-ast`** package version to the latest version
_version changed from 0.2.6 to 0.4.1_

## Bug Checklist
No test added since this is package version update. 

## Feature Checklist

No features added

### CODE REVIEW

**Review by beerose — CHANGES_REQUESTED** [review]
Thank you for the PR!

There are two things to do now:
1. Looks like you didn't commit `pnpm-lock.yaml` file — after running `pnpm i` it should get updated and then you have to include it in this PR.
2. Adding a changeset — run `pnpm changeset` in the root. It will ask a few questions: 1) what packages were updated — select generator, 2) what's the release message — you can type something like "Update prisma-ast dependency".

**Comment by isurumaldeniya** [comment]
@beerose Hi,
Thank you for the wonderful guidance. I have added the lock.yaml file to the PR. But I cannot figure out on the second thing which is Adding changeset. When I tried `pnpm changeset` in root folder, it gives me `'changeset' is not recognized as an internal or external command, operable program or batch file.` Do I need to add a new NPM package ?

**Comment by beerose** [comment]
> @beerose Hi, Thank you for the wonderful guidance. I have added the lock.yaml file to the PR. But I cannot figure out on the second thing which is Adding changeset. When I tried `pnpm changeset` in root folder, it gives me `'changeset' is not recognized as an internal or external command, operable program or batch file.` Do I need to add a new NPM package ?

Hmm, no, you shouldn't need a new package — it should work out of the box. But don't worry about it — I'll add it for you

**Review by beerose — APPROVED** [review]

**Comment by isurumaldeniya** [comment]
@beerose Thank you so much for the guidance. 😄😊 First PR for Open Source is done. Hope to contribute to the project in the future.

**Pull request merged**
