### PR TITLE
Add `useParam` hook

### PR DESCRIPTION
**Pull request by anteprimorac**
Closes: #530 

### What are the changes and their implications?
Adds a new `useParam` hook.

### Checklist

- [x] Tests added for changes
- [x] User facing changes documented

### Breaking change: yes/no
No.

### CODE REVIEW

**Comment by flybayer** [comment]
Beautiful! Can you also update the following two templates to use this?

- https://github.com/blitz-js/blitz/blob/canary/packages/generator/templates/page/__modelIdParam__.tsx
- https://github.com/blitz-js/blitz/blob/canary/packages/generator/templates/page/__modelIdParam__/edit.tsx

**Comment by anteprimorac** [comment]
@flybayer I've updated all generator templates that were using params from `router.query` object.

**Comment by flybayer** [comment]
Awesome, thank you!!!

**Comment by flybayer** [comment]
@anteprimorac one last thing, can you add documentation for this to https://blitzjs.com/docs/route-params-query?

The repo is https://github.com/blitz-js/blitzjs.com. I just gave you commit access

**Comment by flybayer** [comment]
Sweet, thanks again!

@all-contributors add @anteprimorac for docs

**Pull request merged**
