### PR TITLE
update db.ts for #383

### PR DESCRIPTION
**Pull request by nabi009**
I have changed in javascript, plz check typescript if I am not wrong so 

https://github.com/blitz-js/blitz/issues/383

exports.default = Db;
Db.description =`Run database

${chalk_1.default.bold('👉 migrate')}   Run any needed migrations via Prisma 2 and generate Prisma Client.

${chalk_1.default.bold('👉 introspect')}   Will introspect the database defined in db/schema.prisma and automatically \ngenerate a complete schema.prisma file for you. Lastly, it\'ll generate Prisma Client.

${chalk_1.default.bold('👉 studio')}   Open the Prisma Studio UI at http://localhost:5555 so you can easily see and\n change data in your database.
`;

Db.args = [

    {
        name: 'Commands',
        description: Db.description,
        required: true,
    },
   
];

### CODE REVIEW

**Comment by flybayer** [comment]
@nabi009 ah, I just saw this one. You can take the log utils from #409 and add them to this PR. Then we'll just close #409 without merging.

Does that make sense?

**Comment by nabi009** [comment]
> @nabi009 ah, I just saw this one. You can take the log utils from #409 and add them to this PR. Then we'll just close #409 without merging.
> 
> Does that make sense?

sorry, I  removed it.

**Comment by nabi009** [comment]
@0ww @flybayer 
can you help me regarding Prettier errors. thanks

**Comment by flybayer** [comment]
@nabi009 thank you for your help on this!

I'm going to go ahead and close this PR and leave it like it is for now, because this change does improve `blitz db` somewhat, but it makes `blitz db --help` much worse. See below (duplicated content)

```
~/c/b/e/store> blitz db --help
You are using alpha software - if you have any problems, please open an issue here:
  https://github.com/blitz-js/blitz/issues/new/choose

Run database commands

USAGE
  $ blitz db COMMAND

ARGUMENTS
  COMMAND
      Run database commands

      migrate   Run any needed migrations via Prisma 2 and generate Prisma Client.

      introspect   Will introspect the database defined in db/schema.prisma and automatically generate a
      complete schema.prisma file for you. Lastly, it'll generate Prisma Client.

      studio   Open the Prisma Studio UI at http://localhost:5555 so you can easily see and change data
      in your database.

      reset   Reset the database and run a fresh migration via Prisma 2.


OPTIONS
  -h, --help  show CLI help

DESCRIPTION
  migrate   Run any needed migrations via Prisma 2 and generate Prisma Client.

  introspect   Will introspect the database defined in db/schema.prisma and automatically generate a
  complete schema.prisma file for you. Lastly, it'll generate Prisma Client.

  studio   Open the Prisma Studio UI at http://localhost:5555 so you can easily see and change data in
  your database.

  reset   Reset the database and run a fresh migration via Prisma 2.
```

**Comment by flybayer** [comment]
@all-contributors add @nabi009 for code

**Pull request closed without merging**
