### PR TITLE
upgrade monorepo to use yarn v2

### PR DESCRIPTION
**Pull request by flybayer**
### What are the changes and their implications?

This upgrades our yarn version to use v2, but using normal node_modules, not the pnp option.

v2 is configured per repo, so it should upgrade automatically for you

### CODE REVIEW

**Comment by flybayer** [comment]
Ok nevermind, this is ridiculous. Can't even figure out how to get it installed on github actions...

**Comment by JuanM04** [comment]
Are you still interested in using Yarn V2? I can give it a try...

**Comment by flybayer** [comment]
No, I think with the nextjs fork it's better to stay with v1, same as nextjs.

**Comment by merceyz** [comment]
> Ok nevermind, this is ridiculous. Can't even figure out how to get it installed on github actions...

You run `yarn set version berry` and commit the result, there is nothing to do for GitHub Actions - https://yarnpkg.com/getting-started/migration

**Comment by JuanM04** [comment]
I've never checked it, but I think you are having issues because you didn't commit `.yarn/`. [More Info](https://yarnpkg.com/getting-started/qa#which-files-should-be-gitignored).

Nevertheless, maybe it's a good idea to wait until the fork is completely integrated to try changing this

**Pull request closed without merging**
