### PR TITLE
Disable queries until session is loaded.

### PR DESCRIPTION
**Pull request by engelkes-finstreet**
Closes: [1752](https://github.com/blitz-js/blitz/issues/1752)

### CODE REVIEW

**Comment by mtford90** [comment]
Careful with this - because `useSession` does not suspend I found that this fix broke suspense for all usage of `useQuery` - see my further comments in #1752

**Comment by engelkes-finstreet** [comment]
Thank you for the clarification. I misunderstood your comment in the other thread.

**Comment by mtford90** [comment]
no problem @engelkes-finstreet - i had a solution working locally for this within my own project - I just drafted a PR to show you how I handled this:

https://github.com/blitz-js/blitz/pull/1888

**Comment by flybayer** [comment]
Hey @engelkes-finstreet thanks for the attempt, but as I described in https://github.com/blitz-js/blitz/issues/1752, I already tried this and it doesn't work.

The proper fix is to change useSession to use context (which I describe in the issue).

So I'll go and close this :)

**Pull request closed without merging**
