### PR TITLE
Add ability to set custom `authenticateOptions` for the Passport.js adapter

### PR DESCRIPTION
**Pull request by engelkes-finstreet**
### What are the changes and their implications?
Adds an optional parameter `AuthenticateOptions` to BlitzPassportConfig which is used during `passport.authenticate` to pass for example the scope parameter which was missing to get authentication working with Auth0.

New docs: https://github.com/blitz-js/blitzjs.com/pull/155

### CODE REVIEW

**Comment by flybayer** [comment]
@engelkes-finstreet thank you!

One last thing, can you open a PR to the [docs repo](https://github.com/blitz-js/blitzjs.com) to add this to the docs?

**Comment by engelkes-finstreet** [comment]
Yes, of course! Will do it later today.

**Comment by engelkes-finstreet** [comment]
[PR](https://github.com/blitz-js/blitzjs.com/pull/155) for updated documentation @flybayer

**Comment by flybayer** [comment]
Thanks @engelkes-finstreet!

@all-contributors add @engelkes-finstreet for code, docs

**Pull request merged**
