### PR TITLE
Fix: windows slash correction for rpc resolvers

### PR DESCRIPTION
**Pull request by siddhsuresh**
Closes: https://github.com/blitz-js/blitz/issues/4265

### What are the changes and their implications?

Add `slash` to both arguments of `__internal_addBlitzRpcResolver`

## Bug Checklist

- [x] Changeset added (run `pnpm changeset` in the root directory)

### CODE REVIEW

**Comment by siddhsuresh** [comment]
!preview fix-windows-rpc

**Comment by siddhsuresh** [comment]
!preview fix-windows-rpc

**Comment by siddhsuresh** [comment]
!preview fix-windows-rpc

**Comment by siddhsuresh** [comment]
!preview fix-windows-rpc

**Review by flybayer — APPROVED** [review]

**Pull request merged**
