### PR TITLE
Migrate recipes

### PR DESCRIPTION
**Pull request by dillonraphael**
Closes: #3253 

### What are the changes and their implications?
Migrate over recipe functionality from legacy framework.

Some recipes still need to be updated to work with blitz 2.0 (https://github.com/blitz-js/blitz/issues/3813)

## Feature Checklist

Exposes paths such as:
- `nextConfig()`
- `blitzClient()`
- `blitzServer()`

Also exports new helper functions `transformNextConfig()` & `wrapAppReturnStatement()`, 

`transformNextConfig()` returns the following:

```ts
program: Program
configObj: []
pushToConfig: (property: j.ObjectProperty) => void
wrapConfig: (func: string | j.CallExpression) => {
   withBlitz: j.Identifier | j.CallExpression 
}
addRequireStatement: (identifier: string, packageName: string) => void
```

_(`wrapConfig().withBlitz` returns whatever is inside `withBlitz()`)_

`wrapAppReturnStatement()` accepts the following:
```ts
function wrapAppReturnStatement(
  program: Program,
  element: string
)
```
_The element is the name of the react component you want to wrap the return statement with_

- [X] Documentation added/updated https://github.com/blitz-js/blitzjs.com/pull/755

### CODE REVIEW

**Comment by siavashmohammady66** [comment]
When do you think this would be implemented?

**Comment by dillonraphael** [comment]
> When do you think this would be implemented?

I just need to create a util function for transforming `next.config.js`, then I'll set this PR as "Ready for review"

**Comment by Jonovono** [comment]
@dillonraphael any eta for this ? (no rush but thought i'd inquire if it made sense to spend the time to figure out how to install next-ui manually ;p)

**Comment by dillonraphael** [comment]
> @dillonraphael any eta for this ? (no rush but thought i'd inquire if it made sense to spend the time to figure out how to install next-ui manually ;p)

Just about ready. CI is passing. Dealing with an issue in the build process and a package the blitz installer is using.

**Pull request merged**
