### PR TITLE
Export enhancePrisma for client again

### PR DESCRIPTION
**Pull request by medihack**
Closes: #3964

## Bug Checklist

- [x] Changeset added (run `pnpm changeset` in the root directory)
- [ ] Integration test added (see [test docs](https://blitzjs.com/docs/contributing#running-tests) if needed)

## Feature Checklist

- [ ] Changeset added (run `pnpm changeset` in the root directory)
- [ ] Integration test added (see [test docs](https://blitzjs.com/docs/contributing#running-tests) if needed)
- [ ] Documentation added/updated (submit PR to [blitzjs.com repo `main` branch](https://github.com/blitz-js/blitzjs.com))

### CODE REVIEW

**Comment by medihack** [comment]
`enahncePrisma` was removed from the client side by this [merged PR ](https://github.com/blitz-js/blitz/pull/3928). Unfortunately, this leads to a runtime error on the client described in #3964. I am not sure what @beerose issue exactly was with `Exporting it from the browser entry point caused issues when using useSession — Module not found: Can't resolve 'fs'` (never had that one and also using `useSession`), but deleting the export creates a new issue.

**Comment by flybayer** [comment]
Yeah this should be exported from both client and server.

@beerose can you elaborate on what the initial problem was behind https://github.com/blitz-js/blitz/pull/3928 ?

**Comment by beerose** [comment]
> Yeah this should be exported from both client and server.
> 
> @beerose can you elaborate on what the initial problem was behind #3928 ?

I tried to use blitz-auth in a new next app, and the Blitz setup didn't work unless I removed the enhancePrisma from the browser entry point (the error was as mentioned in the PR). Maybe the issue is somewhere else, but it's worth checking if adding it back won't break pure next + blitz-auth apps.

**Comment by flybayer** [comment]
@beerose this does require adding withBlitz() to next.config.js — did you perhaps not have that when you got the error?

**Comment by beerose** [comment]
> @beerose this does require adding withBlitz() to next.config.js — did you perhaps not have that when you got the error?

Yeah, that seems to solve the issue.

**Review by flybayer — APPROVED** [review]

**Pull request merged**
