### PR TITLE
Update Taiwind recipe to opt in to future Tailwind CSS changes

### PR DESCRIPTION
**Pull request by enricoschaaf**
Closes:  #1100 

### What are the changes and their implications?
This pull request updates the Tailwind recipe to automatically opt into all future breaking changes.
### Checklist

- [ ] Tests added for changes
Currently the Tailwind recipe does not have any tests.
- [ ] PR submitted to [blitzjs.com](https://github.com/blitz-js/blitzjs.com) for any user facing changes
There are no user facing changes involved.

### CODE REVIEW

**Comment by flybayer** [comment]
@enricoschaaf looks like you have fixes for both #1100 and #1094 on this same branch/PR. Can you separate them?

**Comment by enricoschaaf** [comment]
Ah, did not know that it works like this, wasnt intended

**Comment by enricoschaaf** [comment]
Should be fixed now😅

**Comment by flybayer** [comment]
Yes, awesome!

@all-contributors add @enricoschaaf for code

**Pull request merged**
