### PR TITLE
blitz-auth: export next-auth adapters

### PR DESCRIPTION
**Pull request by mickamy**
Closes: ?

## Bug Checklist

- [ ] Changeset added (run `pnpm changeset` in the root directory)
- [ ] Integration test added (see [test docs](https://blitzjs.com/docs/contributing#running-tests) if needed)

## Feature Checklist

- [ ] Changeset added (run `pnpm changeset` in the root directory)
- [ ] Integration test added (see [test docs](https://blitzjs.com/docs/contributing#running-tests) if needed)
- [ ] Documentation added/updated (submit PR to [blitzjs.com repo `main` branch](https://github.com/blitz-js/blitzjs.com))

### CODE REVIEW

**Comment by siddhsuresh** [comment]
Hey @mickamy, thanks for the PR, we cannot expose the next-auth plugin directly like this due to the required webpack alias required for it to work.
The required fix to make it work, like in the docs, is made in the PR https://github.com/blitz-js/blitz/pull/4133 and will be released soon.

**Comment by mickamy** [comment]
Thanks, I'm waiting for the coming new release!

**Comment by mickamy** [comment]
@siddhsuresh 
It seems like the issue is still unsolved with the latest version.

https://github.com/blitz-js/blitz/releases/tag/v2.0.0-beta.27

**Comment by siddhsuresh** [comment]
Hey @mickamy , what issue are you facing? Since the required next-auth declaration file is published to npm and can be accessed from @blitzjs/auth/next-auth

**Comment by mickamy** [comment]
Ah, I guess I was just importing em from wrong path.
I'll try it later, thanks for your comment!

**Pull request closed without merging**
