### PR TITLE
[RFC] Blitz File Structure & Routing

### PR DESCRIPTION
**Pull request by flybayer**
The purpose of this RFC (Request for Comments) is to gather as much feedback as possible.

We welcome all feedback, whether good or bad! This is your chance to ensure Blitz meets the needs of your company or project.

### 👉 [View the Rendered RFC](https://github.com/blitz-js/blitz/blob/rfc-structure/rfc-docs/02-file-structure-routing.md) 👈

### CODE REVIEW

**Comment by PullJosh** [comment]
Overall, this looks awesome!

> While you can place any route files [in the top-level routes directory], we recommend placing route files inside `app`. But if you want, you can instead place all your route files in this top level folders instead of being spread out in various directories inside `app`.

I'm struggling to understand the purpose of the top-level routes folder. If I'm not supposed to use it, why is it there?

**Comment by flybayer** [comment]
@PullJosh good question! 

The top level `routes` folder exists for two reasons:
1. Flexibility — for small, simple apps it can be easier to put all your routes here.
2. Ease of converting an existing Next.js app to a Blitz app.

But this is up for debate! We wouldn't have to support this.

**Comment by PullJosh** [comment]
> 2. Ease of converting an existing Next.js app to a Blitz app.

That second point is pretty compelling. In general, this feels like the kind of decision that I don't want to have to make. But if it's presented as a Next.js transition tool, most decisions are still easy as a Blitz user.

**Comment by jamonholmgren** [comment]
I like pretty much everything you’ve detailed here. I especially like the freedom to compose how I want and then Blitz composes it all together at build time.

I would put in a vote for naming it `pages` rather than `routes` — even before I used Next, I liked that nomenclature.

I also like the top level routes(pages) folder, because I could see a use case for some websites being small enough to not warrant splitting into concerns.

**Comment by flybayer** [comment]
@jamonholmgren awesome!

We're proposing `routes` instead of `pages` because:

1. `pages` makes total sense until you add `pages/api/...`. Then you have non-page API routes inside a pages folders which is not ideal
2. Next.js is planning to rename `pages` to `routes` (and support both for backwards compatibility I'm sure)

Anyone else have thoughts on this part?

**Comment by PullJosh** [comment]
> Next.js is planning to rename pages to routes (and support both for backwards compatibility I'm sure)

Interesting! I didn't know that. Where was that future change announced?

**Comment by flybayer** [comment]
@PullJosh it hasn't been announced and there's no planned timeline for it. The way I understood is that it's something they plan to do at some point.

**Comment by flybayer** [comment]
What do you all think about this for the pages/routes folder?

- Keep the folder named `pages` for all your React pages
- Move the `/api/` folder out of pages so it becomes a sibling of `pages`

This preserve the pages name but removes the discrepancy for the non-page files inside api/

```
app/
   products/
      components/
      pages/
      api/
      queries/
      mutations/
```

Now, most apps won’t need the `api/` folder because most code will be in queries and mutations. You only need the api folder if you need a raw Node.js request handler for something custom.

**Comment by MrLeebo** [comment]
It feels off-putting to see queries and mutations next to api. Initial reaction upon seeing it is "those folders belong under api," at least from a graphql interpretation, which isn't the right interpretation but the naming convention makes it an easy mistake to make.

**Comment by wKovacs64** [comment]
I think I prefer the idea of separating them (`pages` and `api` as siblings). Not a big fan of calling it `pages` when they are combined, though (for the [reasons originally mentioned](https://github.com/blitz-js/blitz/pull/74#issuecomment-609171090)), so would vote for `routes` in that case (the original proposal).

**Comment by ryardley** [comment]
I am not sure I have an answer necessarily but I am wondering is it common enough to make it so routes map along context unless you choose to escape it somehow? 

The problem with this system is that there are often repeated folders within the structure.

Eg.

```
app
├── products
│   └── routes
│       ├── admin
│       |   ├── index.tsx
│       |   └── products
│       |       ├── [id].tsx
│       |       ├── index.tsx
│       |       └── new.tsx
│       └── products
│           ├── [handle].tsx
│           └── index.tsx
├── users
│   └── routes
│       └── users
│           ├── [id]/
│           │   └── edit.tsx
│           ├── [id].tsx
│           ├── index.tsx
│           └── new.tsx
└── routes
    ├── about.tsx
    └── index.tsx
``` 

So you get `app/users/routes/users/[id].tsx`

---

What if we leverage convention and used a special folder (maybe `_` ?) to delineate paths originating from root?

```
app
├── products
│   └── routes
│       ├── [handle].tsx
│       ├── _
│       │   └── admin
│       │       └── products
│       │           ├── [id].tsx
│       │           ├── index.tsx
│       │           └── new.tsx
│       └── index.tsx
└── users
    └── routes
        ├── [id]
        │   └── edit.tsx
        ├── [id].tsx
        ├── index.tsx
        └── new.tsx
```

**Comment by flybayer** [comment]
I really like that proposal @ryardley. I think the common case will indeed be for the url path to match the context path.

We could put the special root symbol directly in the first directory/file name instead of the special root symbol being it it's own directory.

```
app
├── products/
│   └── routes/
│       ├──_admin/
│       │       └── products
│       │           ├── [id].tsx
│       │           ├── index.tsx
│       │           └── new.tsx
│       ├── [handle].tsx
│       └── index.tsx
```

Not sure `_` is the best though since this open signifies something internal/not public.

How about `^`?
```
app
├── products/
│   └── routes/
│       ├──^admin/
│       │       └── products
│       │           ├── [id].tsx
│       │           ├── index.tsx
│       │           └── new.tsx
│       ├── [handle].tsx
│       └── index.tsx
```

Or `;`?
```
app
├── products/
│   └── routes/
│       ├──admin/
│       │       └── products
│       │           ├── [id].tsx
│       │           ├── index.tsx
│       │           └── new.tsx
│       ├── [handle].tsx
│       └── index.tsx
```

**Comment by ryardley** [comment]
> We could put the special root symbol directly in the first directory/file name instead of the special root symbol being it it's own directory.

Hmm interesting idea.

I guess it is a personal taste thing and I can see how that could flatten the folder structure but in my head that is an extra mapping and could get noisey with lots of root folders.

```
app
├── widgets/
│   └── routes/
│       ├──^admin/
│       ├──^checkout/
│       ├──^affiliate/
│       ├── [handle].tsx
│       └── index.tsx
```

For me once I am in the `_` folder I am in 'root' land which works basically like next `/pages` with no special rules so it seems simpler.

**Comment by flybayer** [comment]
I just updated this file structure RFC with the following changes:

1. Rename `routes` folder to `pages`
2. Move `routes/api` folder to `api` (`pages` and `api` are now siblings instead of nested)

I think we should hold off on @ryardley' suggestion for changing the url root for nested pages folders. Because, while it reduces nesting for some cases, it increases nesting for others. For example, the file structure example in the RFC has `app/tasks/pages/products/[productId]/tasks/index.ts` which would have to change to `app/tasks/pages/_/products/[productId]/tasks/index.ts`. 

But perhaps there's another way to reduce nesting we haven't thought about that's even more elegant.

**Comment by sijad** [comment]
is it possible to define `_app` and `_document` per `pages/` directories?

is it possible to have `components` folder inside a page and ignored as a route?

```
├── pages
    └── mypage
        ├── components
        │   └── MyPageItem.tsx
        └── index.tsx
```

**Comment by flybayer** [comment]
> is it possible to define `_app` and `_document` per `pages/` directories?

Yes, the following works just like Next.js:
```
app/pages/_app.js
app/pages/_document.js
```

> is it possible to have `components` folder inside a page and ignored as a route?
> 
> ```
> ├── pages
>     └── mypage
>         ├── components
>         │   └── MyPageItem.tsx
>         └── index.tsx
> ```

Currently no, but we could add support to prefix folders with `_`. So you could put `_components/` inside pages without it being counted as a page.

**Comment by ryardley** [comment]
> is it possible to define _app and _document per pages/ directories?

They should be able to be defined in any `pages` folder however I would imagine that best practice would be to keep them in your global `/pages` folder.

**Comment by dwightwatson** [comment]
I find `integrations` to be a little awkward.

I guess `integrations` it's sort of like the `initializers` directory of a Rails app where you're meant to configure third-party clients before the app has booted? Will everything in that directory be auto-loaded by default? The name feels a little too open-ended and I wonder if it even needs to be there by default.

**Comment by flybayer** [comment]
@dwightwatson yes, sort of like Rails, but not autoloaded.

We may drop it as a default before 1.0 if we don't use it, but I expect our installers (RFC #242) will put any type of third-party integration in there.

**Comment by jamonholmgren** [comment]
I'm a big fan of the `/pages` and `/api` siblings. Feels great to me.

**Comment by flybayer** [comment]
This is now documented at [blitzjs.com](https://blitzjs.com)

**Pull request merged**
