### PR TITLE
remove result logging for useQuery/useMutation

### PR DESCRIPTION
**Pull request by hardfire**
### What are the changes and their implications?

This change removes the annoying result log for useQuery/useMutation endpoints

### CODE REVIEW

**Review by Zeko369 — CHANGES_REQUESTED** [review]
While this is a great idea, this should be passed via a config from CLI.
Suggestions / ideas
- DISABLE_LOGS env var or --no-log param in `blitz start`
- Ability to ignore logging of some queries
- Ability to filter some data in logs (similar to how rails does it)
- Also logging to an external JSON file should be setup

@flybayer @ryardley any suggestions/ideas?

**Comment by hardfire** [comment]
@Zeko369 Yes, that was the initial idea to control it using an env. config but somehow decided that this can be removed altogether. 

Since there will be work on the whole logging system in the future, i think (or rather hope) then it would be easy to enable/disable specific logs (or group of logs probably)

Since this discussion was on slack, ill put the screenshot here

image

**Review by Zeko369 — APPROVED** [review]
Then just keep it as is, removed :)

**Comment by flybayer** [comment]
😬 I just now saw this. I overhauled all the logs yesterday in #1212 which already removed logging result data.

Thanks anyways @hardfire!

**Pull request closed without merging**
