### PR TITLE
Replace spinner 2793

### PR DESCRIPTION
**Pull request by johnmurphy01**
Closes: #2793

### What are the changes and their implications?
- Removed `ink-spinner` dependencies
- Replaced `ink-spinner` with `log.spinner` from `@blitzjs`

NOTE: I don't know how to test a recipe locally, so this hasn't been tested. I did run the test scripts however.

## Bug Checklist

- [ ] Integration test added (see [test docs](https://blitzjs.com/docs/contributing#running-tests) if needed)

## Feature Checklist

- [ ] Integration test added (see [test docs](https://blitzjs.com/docs/contributing#running-tests) if needed)
- [ ] Documentation added/updated (submit PR to [blitzjs.com repo](https://github.com/blitz-js/blitzjs.com))

### CODE REVIEW

**Comment by beerose** [comment]
As for the testing, this is what you can do (note: I'm not sure that this is the best way, but it works for me):
1. in root, run `yarn build` to build packages
2. go to `packages/installer` and run `yarn pack` to get a tarball with the installer package
3. go to, for example, `recipes/render` and install it via `yarn add ../../packages/installer/<PATH TO .tar FILE>`.
4. you can then install the recipe, by running `blitz install <path to blitz repo>/recipes/render/index.ts`.

**Review by beerose — COMMENTED** [review]
I'm afraid it won't work because `log.spinner` logs messages to the console, and you use it as a component. 
Here you can find an example usage: https://github.com/blitz-js/blitz/blob/canary/packages/cli/src/commands/install.ts#L238.
I think replacing `Spinner` with `log.spinner` would requires changing the way we handle notifications in installer package — it probably means removing usages of Ink components.

**Comment by 9j** [comment]
> I'm afraid it won't work because `log.spinner` logs messages to the console, and you use it as a component. Here you can find an example usage: https://github.com/blitz-js/blitz/blob/canary/packages/cli/src/commands/install.ts#L238. I think replacing `Spinner` with `log.spinner` would requires changing the way we handle notifications in installer package — it probably means removing usages of Ink components.

That's why I made a temporary plan. #2799
It's being used in too many places in this project to take away the ink
If you want to remove the ink, you need to modify the files that are combined with those two.
It takes an insignificant amount of time compared to the impact.

**Comment by beerose** [comment]
> > I think replacing `Spinner` with `log.spinner` would requires changing the way we handle notifications in installer package — it probably means removing usages of Ink components.
> 
> That's why I made a temporary plan. #2799 It's being used in too many places in this project to take away the ink If you want to remove the ink, you need to modify the files that are combined with those two. Compared to impact, it takes a lot of time.

@9j ee will merge your fix as a temporary workaround, and then we merge @johnmurphy01's PR when it's ready :)

**Comment by johnmurphy01** [comment]
Cool, thanks for the testing steps. This will help.

**Comment by beerose** [comment]
I'm closing this PR — if you or anyone else wants to work on it in the future, feel free to open a new one!

**Pull request closed without merging**
