### PR TITLE
Added eslint import sorting

### PR DESCRIPTION
**Pull request by svobik7**
Closes: #1031

### What are the changes and their implications?

Solves inconsistent imports order in commits by using new eslint plugn https://github.com/lydell/eslint-plugin-simple-import-sort

### CODE REVIEW

**Comment by flybayer** [comment]
Thanks! Can you also enable autofix for this?

**Comment by svobik7** [comment]
@flybayer I see auto-fixing working well before any commit as there is:

```
"husky": {
    "hooks": {
      "pre-commit": "lint-staged && pretty-quick --staged",
    }
  },
  "lint-staged": {
    "*.{js,ts,tsx}": [
      "eslint --fix"
    ]
  },
```

I also have autofixing working after file save but I it is IDE feature.

**Comment by flybayer** [comment]
Ok got it. Then for this PR can you manually run eslint --fix on all files to fix the warnings?

**Comment by svobik7** [comment]
Ok 🙂

**Comment by svobik7** [comment]
All files has been linted/fixed.

**Pull request merged**
