### PR TITLE
Various "blitz new" command improvements 

### PR DESCRIPTION
**Pull request by s-r-x**
Hello.

Closes: #2694 

- package manager prompt(npm, yarn, pnpm, skip). yarn and pnpm are visible only if they are installed. if only npm is available the prompt is simple as that "install dependencies (yes/no)". with "skip-install" cli flag the prompt is not shown. default package manager depends on the available list of installed package managers(yarn > pnpm > npm).
- pnpm "blitz new" cli flag
- remove message "We had some trouble connecting to the network..." on blitz new, that pops out even if "skip install" flag has been passed to the app generator
also i refactored the commands/new file a little bit to make it more readable

https://user-images.githubusercontent.com/41614937/133230124-f4fe40d2-950a-4463-af2f-b3c09e1c1433.mp4

## Bug Checklist

- [ ] Integration test added (see [test docs](https://blitzjs.com/docs/contributing#running-tests) if needed)

## Feature Checklist

- [ ] Integration test added (see [test docs](https://blitzjs.com/docs/contributing#running-tests) if needed)
- [ ] Documentation added/updated (submit PR to [blitzjs.com repo](https://github.com/blitz-js/blitzjs.com))

### CODE REVIEW

**Review by flybayer — COMMENTED** [review]
@s-r-x awesome, thank you!! And I'm so sorry for the long delay here.

Only thing I see is that I think pnpm should be default if installed. What do you think?

**Comment by flybayer** [comment]
@s-r-x sure, you can add that!

**Comment by s-r-x** [comment]
@flybayer done

https://user-images.githubusercontent.com/41614937/134292607-5fb4a418-aa76-4b6e-878a-694d3a8cc962.mp4

**Comment by flybayer** [comment]
Beautiful, thank you so much!!

**Pull request merged**
