### PR TITLE
doc: Describe precise version of node.js

### PR DESCRIPTION
**Pull request by tarunama**
### What are the changes and their implications?
describe precise version of node.js in [Getting started](https://blitzjs.com/docs/getting-started)

### Checklist

- [ ] Tests added for changes
- [ ] PR submitted to [blitzjs.com](https://github.com/blitz-js/blitzjs.com) for any user facing changes

### CODE REVIEW

**Comment by flybayer** [comment]
@tarunama as far as I know any v12 version and up works. The `.node-version` setting is just a convenience, not a requirement.

**Comment by tarunama** [comment]
@flybayer 
I have misunderstood. Thank you for your review !

**Comment by nitaking** [comment]
@flybayer 
There is the following in `package.json/engines`, which causes an error with yarn in node v12.20 and below. (or npm install --engine-strict)

This means that if you want to use node v12.20 or above as a development environment, you need to make sure that it works as well.
Ideally, package.json/engines should be set to `"node":">=12"` if you want to use 12 or more. What do you think? (The
 .node-version is fine as it is)

```json
  "engines": {
    "node": ">=12.20.0"
  },
```

https://github.com/blitz-js/blitz/blob/9536caa07383847e400a686a3bb2e2b216476bb5/package.json#L16

```bash
 $ yarn
yarn install v1.22.4
[1/5] 🔍  Validating package.json...
error root@0.0.0: The engine "node" is incompatible with this module. Expected version ">=12.20.0". Got "12.17.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by flybayer** [comment]
Oh good point, then we should change that to just be `>=12`

**Pull request closed without merging**
