### PR TITLE
fix `getQueryKey()` to work on  the server (patch)

### PR DESCRIPTION
**Pull request by jxe**
Closes: #1567 

### What are the changes and their implications?

This fix 
* (a) makes getQueryKey work on the server; 
* (b) makes useQuery work on the server if the query is already pre-cached, but the query won't run otherwise. 

(b) is relevant to #1530.

### CODE REVIEW

**Comment by jxe** [comment]
Hmmm, looks like I broke things. I guess the problem is that react-query isn't suspending on the server side, and it should. I'm not sure if there's an API to make rq suspend on enabled:false or when idle. But I guess this could be done in the useQuery wrapper before it returns. But this means, I think, using the top-secret suspense data fetching api inside the useQuery wrapper? (That is, it should [throw a suspender](https://github.com/gaearon/suspense-experimental-github-demo/blob/master/src/api.js)?)

**Comment by jxe** [comment]
I can't tell why that windows CI build failed.

My rather hacky second commit makes this work for my own purposes. There are some problems with it, that I don't intend to fix:

1. react-query's 'isLoading' should perhaps be set to true on the server. But with my approach the query isIdle on the server, but not isLoading.
2. I didn't mod blitz's useInfiniteQuery and usePagedQuery, just useQuery
3. It's kind of ugly
4. My dirty little implementation of placeholderData doesn't work the same as the implementation in react query 3

However, it lets me do what I wanted: write isomorphic useQueries on the server and client and pass the queryCache from server to client. I'm happy to live on my own little branch for a while until this gets implemented in a better way in blitz proper.

**Comment by flybayer** [comment]
Hey thanks! The windows example CI is currently busted. Not sure what's the deal with it.

Could you do the queryKey fix separately? Then we can go ahead and ship that. Have to think about the placeholder thing. Might be good to wait till RQ v3 upgrade, maybe some things will work better after that.

Btw, in the meantime you can use https://github.com/ds300/patch-package to patch the blitz source code in your app to get what you want.

**Comment by flybayer** [comment]
@jxe are you interested in reworking this PR to jest fix the getQueryKey issue?

> Ok yeah we can rework that a bit so that `emptyQueryFn` is only returned for use by useQuery hooks but not by `getQueryKey`

**Comment by jxe** [comment]
OK, I redid it, without the placeholder stuff, as you asked. I still didn't patch usePaginatedQuery and useInfiniteQuery, so this is incomplete. But perhaps you can merge it, and someday follow my lead with the other queries, and also rewrite your routerIsReady stuff to work like what I did—using enable:false rather than a fake queryFn. I think fake queryFns are a bad idea.

**Comment by flybayer** [comment]
Hey @jxe, this still has changes to the query hooks which is what I was asking you to remove.

We can't use `enabled:false` because that also disable suspense. The router is ready fake query fns are the only known solution to that.

**Comment by jxe** [comment]
@flybayer oh I guess I still don't understand. 

- If I just change getQueryKey, server side useQuery will execute during server rendering. So something inside useQuery must disable them. 
- I disabled them this way (rather than with a fake queryFn) because I do prefetching in my SSG. If the queries have been prefetched, the SSG useQuery should return data. By setting enabled:false, I get it to return data in this case, but not run otherwise.

Also, re your second point, it seems to me that using a fake queryFn is equivalent to what I've done (`throw new Promise(() => {})`). Is that not true?

**Comment by flybayer** [comment]
@jxe fyi you need to merge latest canary into this branch which has some changes here because `useSession` now uses suspense by default.

I agree that this change adds the functionality removed from `sanitize`:
```
const routerIsReady = useRouter().isReady || isServer
```

But then you don't need the `enabled` override or the manual `throw promise` because react-query will throw the promise on the server.

**Comment by flybayer** [comment]
> I disabled them this way (rather than with a fake queryFn) because I do prefetching in my SSG. If the queries have been prefetched, the SSG useQuery should return data. By setting enabled:false, I get it to return data in this case, but not run otherwise.

Fixing useQuery to work with SSG is a separate issue. I'm definitely interesting in fixing this, but I'd rather take that up in a separate PR because trying to fix both at once is making it confusing :D

**Comment by jxe** [comment]
@flybayer I think to disable on the server that line should be `const routerIsReady = useRouter().isReady && isClient`

Sure, I can make this PR just do that and send another one that lets useQuery work (if it has precached data) during SSG.

**Comment by flybayer** [comment]
Awesome, thank you!

**Comment by jxe** [comment]
OK, @flybayer here's PR #1, with just the getQueryKey fix

**Comment by flybayer** [comment]
Sweet, thank you!!

@all-contributors add @jxe for code

**Pull request merged**
