### PR TITLE
feat(cli): add href property to RouteURLObject

### PR DESCRIPTION
**Pull request by a11rew**
Closes: #2829, #2816 

### What are the changes and their implications?
Adds an href property to the Route objects generated in the Route Manifest. 
This href property represents a pathname with the query parameters filled out.

pathname: `projects/[projectID]/users/[userID]/edit`
href: `projects/test-project/users/test-user/edit`

This href could be used in `res.redirect` or canonical URL tags.

## Bug Checklist

- [ ] Integration test added (see [test docs](https://blitzjs.com/docs/contributing#running-tests) if needed)

## Feature Checklist

- [ ] Integration test added (see [test docs](https://blitzjs.com/docs/contributing#running-tests) if needed)
- [ ] Documentation added/updated (submit PR to [blitzjs.com repo `canary` branch](https://github.com/blitz-js/blitzjs.com/tree/canary))

### CODE REVIEW

**Comment by a11rew** [comment]
@dillonraphael from my testing, in dev linking the cli package to another app does not change where the processes are run so the declarations are not changed. i.e. this call causes the updated declaration and implementations for the route manifest to be output into the blitz packages's node_modules. Not the app it is linked to
https://github.com/blitz-js/blitz/blob/a6e81f156bedf0def9c7b6cd1f856df64e981841/packages/blitz/src/cli/utils/routes-manifest.ts#L518

That might be why you're not seeing the href in the declarations of the app you use to test. I got around that by temporarily hardcoding the path to my apps .blitz folder in node_modules. Screenshot of route with proper type declarations attached
Screenshot from 2022-10-18 09-13-35

 This shouldn't be an issue when this is merged though since like with the other route manifest methods and properties it'll be generated from the app's copy of blitz.

Regarding the manifests not being generated with `dev` but with `codegen`, I think they're actually generated but into the wrong location because of the above.

And as far as I can tell, `blitz dev` and `blitz codegen` call the same manifest generator function so there shouldn't be any difference in what they output (?). I'd appreciate pointers if otherwise 
https://github.com/blitz-js/blitz/blob/a6e81f156bedf0def9c7b6cd1f856df64e981841/packages/blitz/src/cli/utils/routes-manifest.ts#L583-L585

https://github.com/blitz-js/blitz/blob/a6e81f156bedf0def9c7b6cd1f856df64e981841/packages/blitz/src/cli/utils/codegen-tasks.ts#L32

**Comment by a11rew** [comment]
Hi @dillonraphael @beerose, a look here? :sweat_smile:

**Comment by dillonraphael** [comment]
Hey sorry @a11rew! Long overdue response. If you patch the path to your apps .blitz folder in node_modules, did blitz dev work? 

The thing is, when I run blitz codegen, it updates the route manifest correctly (with the href property). But once I run blitz dev, I can see the same file being overwritten which makes me believe it's not so much an issue with finding `.blitz`.

But yes I agree that this odd since both blitz dev & blitz codegen are calling the same routes-manifest function.

**Comment by a11rew** [comment]
Yes @dillonraphael `blitz dev` and `blitz codegen` worked the same - they both add the href property. Weird they don't work the same for you, maybe you don't have this version of the cli (with the href addition) linked? 

Here I have a standalone blitz project, with the cli symlinked with pnpm and the `dotBlitz` path patched like so - 
image


https://user-images.githubusercontent.com/87580113/200022612-f489b589-09b1-4f42-a8e1-af7e2486ffe2.mp4

**Comment by dillonraphael** [comment]
> Yes @dillonraphael `blitz dev` and `blitz codegen` worked the same - they both add the href property. Weird they don't work the same for you, maybe you don't have this version of the cli (with the href addition) linked?
> 
> Here I have a standalone blitz project, with the cli symlinked with pnpm and the `dotBlitz` path patched like so - image
> 
>  2022-11-04.15-58-26.mp4

Interesting. I'll try again.

**Comment by jeliasson** [comment]
Any updates on this? Would love to see the `.href` property.

**Review by dillonraphael — APPROVED** [review]

**Pull request merged**
