### PR TITLE
Fix prefetching, again...

### PR DESCRIPTION
**Pull request by Zeko369**
Will this finally fix it or not? :(

### CODE REVIEW

**Comment by beerose** [comment]
Could you explain briefly what was wrong and why this change fixes it? Because at first glance, it looks like it should do the same thing

**Comment by Zeko369** [comment]
@beerose That's why I though the original one would work without testing, but it didn't 😅.

So, the old version returns the reference to the variable which CAN be reassigned in the prefetchQuery functions -> causing the returned variable to have the old value (null) instead of the new QueryClient.
Having a lambda that can be called after the fact will in turn always return the current value.

**Comment by beerose** [comment]
Okay, thanks. Have you tested it or should I?

**Comment by Zeko369** [comment]
I tested this and it works

**Review by beerose — APPROVED** [review]

**Pull request merged**
