### PR TITLE
Update `findModuleExportsExpressions` installer transform utility

### PR DESCRIPTION
**Pull request by wKovacs64**
Closes: N/A

### What are the changes and their implications?

@kevinlangleyjr updated `findModuleExportsExpressions` in #2112 for individual recipes. This updates the shared transform to that implementation.

### Checklist

- [ ] Changes covered by tests (tests added if needed)
- [ ] Does this PR warrant documentation updates? If yes, open a second PR with doc changes to [blitzjs.com](https://github.com/blitz-js/blitzjs.com)

### CODE REVIEW

**Comment by wKovacs64** [comment]
Pretty sure this test is trash, actually. Looking into it...

**Comment by wKovacs64** [comment]
Yep, no idea how to test this actually - test removed. 😅

**Comment by wKovacs64** [comment]
This originally passed all CI jobs...

**Comment by flybayer** [comment]
Sweet, thanks!

**Pull request merged**
