### PR TITLE
Fix top level await in `blitz console` 🎉

### PR DESCRIPTION
**Pull request by wKovacs64**
Closes: #230
Closes: #243

### What are the changes and their implications?

Spawns a separate `node` process for CLI commands, explicitly passing `--experimental-repl-await` to the new child process.

This currently spawns a new process for every command, when it might only be useful for `console` (at this time). We could add some logic that checks to see if the command is `console` and only spawn the new process in that case, but I'm not sure if the added noise is worth it.

### Checklist

- [ ] Tests added for changes
- [ ] PR submitted to [blitzjs.com](https://github.com/blitz-js/blitzjs.com) for any user facing changes

I've manually tested this with Node 12 on macOS Catalina, Windows 10, and Linux Mint Tessa.

I can open a PR to the docs site to replace all the `.then` references with `await` syntax if we decide to merge this.

### CODE REVIEW

**Comment by flybayer** [comment]
Awesome!!! Looks great. I can't test it at the moment, but I'll try to a bit later. Maybe @aem can verify.

**Comment by aem** [comment]
@flybayer I can't merge since this touches a file outside of the packages I'm codeowner for, but it's good to go

**Comment by wKovacs64** [comment]
Cool. I'll work on updating the examples in the docs tomorrow.

**Comment by flybayer** [comment]
@wKovacs64 that'd be great, thank you!

**Pull request merged**
