### PR TITLE
Fix useQuery hooks return type when `enabled` or `suspense` could be false (patch)

### PR DESCRIPTION
**Pull request by LBrian**
Closes: ??

### What are the changes and their implications?
As the issue #1874, currently `data` of `useQuery` type is always casted to `TResult` which is not implied the actual union type of `data`, also there is no `resolvedData` in `InfiniteQueryResult` but `data`.

### Checklist

- [x] Changes covered by tests (tests added if needed)
- [x] PR submitted to [blitzjs.com](https://github.com/blitz-js/blitzjs.com) for any user facing changes

### CODE REVIEW

**Comment by flybayer** [comment]
Hey @LBrian thank you for the effort on this. Currently we have the types optimized for the case when you are using suspense, and we want to keep that. The type change you have here is a regression for our "happy path" (with suspense).

So the correct fix is to adjust the return type such that result is only possibly undefined if `suspense: false` or `enabled: false`

**Comment by LBrian** [comment]
> regression



> Hey @LBrian thank you for the effort on this. Currently we have the types optimized for the case when you are using suspense, and we want to keep that. The type change you have here is a regression for our "happy path" (with suspense).
> 
> So the correct fix is to adjust the return type such that result is only possibly undefined if `suspense: false` or `enabled: false`

Hi @flybayer, thanks for the feedback. I aware the "happy path" is intentional and was thinking to just fix for the cases, but I had put myself into conundrums in the past by casting type intentionally for "happy cases" and that's why I suggested a regression solution. Anyway, I can totally understand and will revert my solution.

**Comment by LBrian** [comment]
I believe we don't need to handle `suspenseEnabled` in the `blitz.config.js` since we only expect TS raise error when explicit `suspense: false` and `enabled: false`

**Comment by flybayer** [comment]
Sweet, very nice!!! I just pushed a commit that makes it even stricter, so that result includes undefined unless suspense and enabled are explicitly `true`. If they are set to a variable, then result will include undefined since we don't know what the variable will be at runtime.

**Comment by flybayer** [comment]
@all-contributors add @LBrian for code

**Review by flybayer — APPROVED** [review]

**Pull request merged**
