### PR TITLE
Change "Zeit" to "Vercel"

### PR DESCRIPTION
**Pull request by 0xflotus**
According to their [statement](https://vercel.com/blog/zeit-is-now-vercel), Zeit is now Vercel. So I changed the needed Zeit account to Vercel account :)

### CODE REVIEW

**Comment by merelinguist** [comment]
Thank you for this @0xflotus ! 💜

**Comment by 0xflotus** [comment]
> There are a few more references to Zeit across the codebase, do you think you could fix these as well?
> 
> https://github.com/blitz-js/blitz/search?q=zeit&unscoped_q=zeit

Is it right now?

**Comment by merelinguist** [comment]
@0xflotus Thank you! Can you just resolve the conflicts and then we can merge?

**Comment by flybayer** [comment]
Thank you @0xflotus! 

@all-contributors add @0xflotus for code and docs

**Pull request merged**
