### PR TITLE
Fix server tests not running on windows

### PR DESCRIPTION
**Pull request by dajinchu**
### Type: bug fix

Closes: #345 

### What are the changes and their implications? :gear:

Use resolve and relative paths with mockfs so we don't have issues between `/dev` and `C:\dev`. 
😡 Windows :rage:

### Checklist

- [ ] Tests added for changes
- [ ] Any added terminal logging uses `packages/server/src/log.ts`

### Breaking change: no

### CODE REVIEW

**Comment by ryardley** [comment]
I don't have a win vm on my machine @wKovacs64 can you help review this?

**Comment by dajinchu** [comment]
yeah, we could try something with https://www.npmjs.com/package/unionfs if needed. It plays nicely with `mock-fs`. 

Not sure where we could document this, but the workaround for console.log is to reference `console` anywhere before the mock happens, and then it will work even after mock.

**Comment by wKovacs64** [comment]
I tried a unionfs/memfs combo, but ran into trouble (don't recall what exactly, would have to revisit), but that type of overlay approach would probably be better than a pave-over. Maybe unionfs/mock-fs is the magic pairing. 🤷‍♂️

**Comment by ryardley** [comment]
Sounds like this solves our immediate problem but we need to revisit the approach

**Comment by wKovacs64** [comment]
Can we get this merged for now @flybayer? We'll circle back in #352.

**Pull request merged**
