### PR TITLE
ci: run tests on both Windows and Ubuntu

### PR DESCRIPTION
**Pull request by wKovacs64**
### Type: tests 

Closes: #188

### What are the changes and their implications? :gear:

Modified the main CI workflow to run against an OS matrix including `ubuntu-latest` and `windows-latest` (Windows Server 2019 at the time of this PR).

### Checklist

- [x] Tests added for changes
- [ ] Any added terminal logging uses `packages/server/src/log.ts`

### Breaking change: no 

N/A

### Other information

N/A

### CODE REVIEW

**Comment by flybayer** [comment]
@wKovacs64 awesome! Did you look at what's currently failing on the windows CI?

**Comment by wKovacs64** [comment]
Briefly, but I can't reproduce it on Windows 10 locally. I should have more time tomorrow to investigate further.

**Comment by flybayer** [comment]
Ok cool, mark as ready for review when done

**Comment by wKovacs64** [comment]
Do we want all Windows issues resolved before merging this so we start with a fully passing CI?

**Comment by flybayer** [comment]
Good question — what do you think we should do?

**Comment by wKovacs64** [comment]
I guess there's no point in merging before we clear up the known issues, or every PR going forward will fail CI. 😄

**Comment by wKovacs64** [comment]
Fixed the lint issue by enforcing LF line endings at the repository level (Git for Windows defaults to auto convert to CRLF, which was causing eslint to stroke out). This should really be in the repo regardless of CI, so let me know if you'd prefer a separate PR for just that and I'll extract it out.

Anyway, now we're only failing on known issues so... that's... good... I guess... heh.

**Comment by wKovacs64** [comment]
This is finally ready! 

I think someone with repository settings access may need to adjust the branch protection rules, as the "Build & Test" job is now two separate checks. See https://github.community/t5/GitHub-Actions/Expected-Waiting-for-status-to-be-reported/m-p/52179#M8428.

**Comment by flybayer** [comment]
Yay!!!

**Pull request merged**
