### PR TITLE
3811 move useCurrentUser hook

### PR DESCRIPTION
**Pull request by estevanjantsk**
Closes: #3811 

### What are the changes and their implications?

useCurrentUser should be moved from `core/hooks` to `users/hooks`

Changed location for:

- toolkit-app
- toolkit-app-passport
- generator

## Bug Checklist

- [ ] Integration test added (see [test docs](https://blitzjs.com/docs/contributing#running-tests) if needed)

## Feature Checklist

- [ ] Integration test added (see [test docs](https://blitzjs.com/docs/contributing#running-tests) if needed)
- [ ] Documentation added/updated (submit PR to [blitzjs.com repo `canary` branch](https://github.com/blitz-js/blitzjs.com/tree/canary))

### CODE REVIEW

**Review by dillonraphael — APPROVED** [review]

**Comment by estevanjantsk** [comment]
hey @dillonraphael how can I rerun the test? It looks like it's unstable. I don't think it's related to my changes.

**Comment by dillonraphael** [comment]
> hey @dillonraphael how can I rerun the test? It looks like it's unstable. I don't think it's related to my changes.

@estevanjantsk Can you try pulling the latest from main and merging it into your PR?

**Review by beerose — APPROVED** [review]
Thanks a lot for contributing! Looks great.

Could you also update the docs? There are two relevant files: 
1. https://github.com/blitz-js/blitzjs.com/blob/bbfd65b233bc0ef08f17676407c99aa0fc2c15e6/app/pages/docs/file-structure.mdx
2. https://github.com/blitz-js/blitzjs.com/blob/e72f8dbab76cf9232808401d3be444bd34f0e6e8/app/pages/docs/tutorial.mdx

**Comment by estevanjantsk** [comment]
@beerose will create the other PR.

**Pull request merged**
