### PR TITLE
Fix For Regex in PagesPathTransformer Function

### PR DESCRIPTION
**Pull request by Patil2099**
Fixes ##2341 
 @flybayer I came up with this regex. If you have another solution please suggest. 

Thanks!

### CODE REVIEW

**Comment by flybayer** [comment]
@Patil2099 thank you! Sorry for the long delay here, was on vacation.

Can you please add at least one test case to test file for this function? See https://github.com/blitz-js/blitz/issues/2341#issuecomment-842663083

Also next time, please don't delete the PR template.

**Comment by flybayer** [comment]
@Patil2099 are you able to finish this?

**Comment by Patil2099** [comment]
Sorry. I forgot about it I will make the required changes soon.

**Comment by flybayer** [comment]
This was fixed in https://github.com/blitz-js/blitz/pull/2502

**Pull request closed without merging**
