### PR TITLE
Fix Glob in GUI for Windows

### PR DESCRIPTION
**Pull request by MykalMachon**
Closes: #607 

### What are the changes and their implications?
updated the getDirMTime function in blitz/gui with a windows specific glob regex, making it functional on Mac & Windows

### Checklist

- [x] Tests added for changes (N/a as this was a bug-fix)
- [x] User facing changes documented (N/a as this was a bug-fix)

### Breaking change: yes/no
no

### Other information
Not anything I can think of! This was a pretty simple bugfix.
I just added a special case for when `process.platform === 'win32'` to update the path/regex string to be windows compatible.

### CODE REVIEW

**Comment by Zeko369** [comment]
@MykalMachon Why not use path.resolve here?

**Comment by MykalMachon** [comment]
@Zeko369 just looked into that, and that definitely seems to be a more concise solution as it doesn't introduce platform specific cases. **I'm not super familiar with node's path module; thanks for the tip!**

The reason I used the solution I did is that it was referenced in the initial issue as a solution to the cross platform issue (See the linked glob docs in #607). 

I'll make another commit after work today to resolve this :smile:

**Comment by MykalMachon** [comment]
So after some further testing, it seems that **neither `path.resolve` or `path.normalize` worked on windows as solutions.** 

However, my previous solution that utilizes javascript's `replace()` function did work on both my windows machine and my Linux VM, so I removed the platform-specific check but kept my previous solution. 

I might be doing something wrong here, as you would think the inbuilt node APIs would account for handling the path string properly but it seems that's not the case? **would be more than open to some more feedback here if this still isn't a solid enough solution 😃** 

### Test Output For Reference
Here are the results of the testing I did across approaches and platforms, I generated the glob string on both Windows and Linux and logged the resulting path string and whether it worked or not. 

#### `replace()` function
Windows
` C:/Users/mykal/blitz-projects/tester/{,!(node_modules|.blitz|.git)/**/}*.* (WORKED)` ✔️ 

Linux
` C:\Users\mykal\blitz-projects\tester\{,!(node_modules|.blitz|.git)\**\}*.* (WORKED)` ✔️ 

#### `path.normalize` function
Windows
`C:\Users\mykal\blitz-projects\tester\{,!(node_modules|.blitz|.git)\**\}*.* (DID NOT WORK)` ❌ 

Linux
`C:\Users\mykal\blitz-projects\tester\{,!(node_modules|.blitz|.git)\**\}*.* (WORKED)` ✔️ 

#### `path.resolve` function
Windows
`C:\Users\mykal\blitz-projects\tester\{,!(node_modules|.blitz|.git)**}*.* (DID NOT WORK)` ❌ 

Linux
`C:\Users\mykal\blitz-projects\tester\{,!(node_modules|.blitz|.git)\**\}*.* (WORKED)` ✔️

**Comment by merelinguist** [comment]
Thanks for all the detail @MykalMachon! I just tested this on my Mac, and it worked perfectly too! Great job. 🎆

**Pull request merged**
