### PR TITLE
Update Next.js to 9.4! (requires react 0.0.0-experimental-33c3af284)

### PR DESCRIPTION
**Pull request by Zeko369**
### Type: feature

Closes: #495

### What are the changes and their implications? :gear:

Get new next features
- React Fast Refresh
- fetch polyfill for node 

### Breaking change: no

### CODE REVIEW

**Comment by flybayer** [comment]
@Zeko369 what was the issue with the react experimental version? We had it pinned to an old version because it the latest version breaks a simple button onClick 😬 

https://blitzjs.slack.com/archives/C011EQ0J75M/p1588869939234600https://blitzjs.slack.com/archives/C011EQ0J75M/p1588869939234600

**Comment by Zeko369** [comment]
So just rerunning it fixed it, somehow 😕??

**Comment by merelinguist** [comment]
Is this ready to merge @Zeko369 ?

**Comment by Zeko369** [comment]
@merelinguist Yes

**Pull request merged**
