### PR TITLE
Fix optional catch-all handling in routes codegen

### PR DESCRIPTION
**Pull request by kirakik**
Closes: #2286

### What are the changes and their implications?

See the issue for more details, this is essentially fixing the build for projects with optional catch all routes.

## Bug Checklist

- [ ] Integration test added (should I add an integration test for this somewhere?)

### CODE REVIEW

**Review by Skn0tt — CHANGES_REQUESTED** [review]
Great work on adding all of the tests.
I don't think an integration test is necessary. WDYT @flybayer?

This PR only fixes parsing, we should also adapt the code generation part to actually mark the optional parameters as being optional.

**Comment by kirakik** [comment]
> This PR only fixes parsing, we should also adapt the code generation part to actually mark the optional parameters as being optional.

Where can I find the code generation part in the codebase?

**Comment by Skn0tt** [comment]
It's in the same file 😊 https://github.com/blitz-js/blitz/blob/ada8e2d4255ac6d0cfdd3084827edec6ed37510c/packages/server/src/stages/route-import-manifest/route-import-manifest.ts#L49

**Comment by Skn0tt** [comment]
Awesome PR @kirakik!!!

**Pull request merged**
