### PR TITLE
Update favicon for new apps to be orange version of the blitz logo

### PR DESCRIPTION
**Pull request by Roesh**
Closes: #2544

### What are the changes and their implications?
This is a small quality of life change. Updating the blitz logo to look orange instead of purple so that we can distinguish out localhost blitz app from the blitz documentation website. This is similar to the example of Hasura provided in the linked issue:
image
New orange favicon:
image

If needed, I have a 128x128 and 32x32 png versions and can upload them to any appropriate locations for future reference

128x128 version:
128x128-Favicon-Orange
32x32 version
32x32-Favicon-Orange
## Bug Checklist

- [ ] Integration test added (see [test docs](https://blitzjs.com/docs/contributing#running-tests) if needed)

## Feature Checklist

- [ ] Integration test added (see [test docs](https://blitzjs.com/docs/contributing#running-tests) if needed)
- [ ] Documentation added/updated (submit PR to [blitzjs.com repo](https://github.com/blitz-js/blitzjs.com))

### CODE REVIEW

**Review by JuanM04 — APPROVED** [review]
Nice! I love DX improvements like this

**Comment by Roesh** [comment]
Thanks!

I accidentally uploaded my blitz env vars variable though, (the last commit) :((

I'm working on the unit test and integration test for that on a separate branch now, let me see the best way to revert a commit on github

**Review by JuanM04 — APPROVED** [review]
Thanks!

**Comment by JuanM04** [comment]
> I accidentally uploaded my blitz env vars variable though

I thought it was an error of the git history :smile:

**Pull request merged**
