### PR TITLE
Add ability to prefetch query data

### PR DESCRIPTION
**Pull request by ivandevp**
Closes: #237

### Checklist

- [ ] Tests added for changes
- [ ] User facing changes documented

### CODE REVIEW

**Comment by flybayer** [comment]
Thank you for your work on this @ivandevp!

There's one more change needed (it's not working as is). You need to also use the query parameters for the actual cache key. See [this line](https://github.com/blitz-js/blitz/blob/canary/packages/core/src/use-query.ts#L23) for the exact query cache key. It's probably worth breaking that out into a utility function that we can use anytime we need the full cache key.

**Comment by ivandevp** [comment]
You're right @flybayer! Will make the change.

**Comment by ivandevp** [comment]
Hey @flybayer ! I've updated the PR to use the params in the query cache key 😃

**Comment by flybayer** [comment]
Awesome, thanks @ivandevp! I'll test this tomorrow :)

**Comment by flybayer** [comment]
Ok, this works great! It was also making extra calls for normal `useQuery` usage, so I pushed a fix for that and also added this to the store example.

Thank you for your help on this!

**Pull request merged**
