### PR TITLE
WIP: #966 running Blitz behind SSL proxy

### PR DESCRIPTION
**Pull request by PixelsCommander**
Closes: #966 running Blitz behind SSL proxy

### Checklist

- [ ] Tests added for changes
- [ ] PR submitted to [blitzjs.com](https://github.com/blitz-js/blitzjs.com) for any user facing changes

### CODE REVIEW

**Comment by flybayer** [comment]
Hey @PixelsCommander, did you mean to close this PR?

**Comment by PixelsCommander** [comment]
Yes, I was not able to test this yet because of blitz contribution setup issues so decided to close the PR and open back once tested.

**Comment by flybayer** [comment]
@PixelsCommander ok, what issues were you having?

**Comment by PixelsCommander** [comment]
After solving some build errors yesterday I am left with "blitz" module not found when running auth example. Another way to test is to link my fork to my application but not figured yet how to link it properly considering it is lerna

**Pull request closed without merging**
