### PR TITLE
feat(cli): add help for db commands

### LINKED ISSUE #135: Add help information to `blitz db` command
Currently `blitz db` and `blitz db -h` both print an error about an unsupported command.

Both of these should print a list of supported commands.

The alpha user guide lists the supported `blitz db` commands: https://github.com/blitz-js/blitz/blob/flybayer-patch-1/USER_GUIDE.md#blitz-cli-commands

### PR DESCRIPTION
**Pull request by sijad**
fixes #135

### CODE REVIEW

**Comment by sijad** [comment]
I think it's better to use [topics](https://oclif.io/docs/topics) but commands would be like `db:migrate`, `db:introspect`

**Comment by flybayer** [comment]
@sijad yeah, I really want the "db migrate" format instead of "db:migrate".

At some point we need to build a nice abstraction that makes it easy to support these without ugly code :)

**Comment by flybayer** [comment]
Can you add more detailed help for each db command? I.e. basically what I have here: https://github.com/blitz-js/blitz/blob/flybayer-patch-1/USER_GUIDE.md#blitz-cli-commands

**Comment by tsawan** [comment]
would be nice to support "db migrate" and "db m".

**Comment by sijad** [comment]
currently it looks like this:

2020-04-17-16:49:23-screenshot

please let me know what you think

**Comment by flybayer** [comment]
Yeah, that works. Thank you!!

@all-contributors add @sijad for code

**Pull request merged**
