### PR TITLE
Remove "--experimental" from "blitz db studio"

### PR DESCRIPTION
**Pull request by brunocrosier**
Running `blitz db studio` outputs `warn --experimental is no longer required for this command` to the terminal

I guess this is since Prisma made Studio stable, so `experimental` is no longer required.

Closes: ??

### Checklist

- [ ] Tests added for changes
- [ ] PR submitted to [blitzjs.com](https://github.com/blitz-js/blitzjs.com) for any user facing changes

### CODE REVIEW

**Review by engelkes-finstreet — DISMISSED** [review]
Thank you @brunocrosier! Works like a charm 🚀

**Comment by flybayer** [comment]
@brunocrosier thanks! Just need to also update the corresponding test (as you can see, CI is failing)

**Comment by brunocrosier** [comment]
@flybayer sorry i don't really know how to do that to be honest!

**Comment by flybayer** [comment]
@brunocrosier sure thing, all you have to do is update this line: https://github.com/blitz-js/blitz/blob/canary/packages/cli/test/commands/db.test.ts#L191

**Comment by brunocrosier** [comment]
OK hopefully that's done now @flybayer !

**Pull request merged**
