### PR TITLE
chore(prtemplate): create a PR Template for the project.

### PR DESCRIPTION
**Pull request by ETLopes**
## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Build (`yarn build`) was run locally and any changes were pushed
- [ ] Lint has passed locally and any fixes were made for failures
- [ ] Code Coverage stayed the same or increased

## Pull request type

:boom: Please check the type of change your PR introduces :boom: :

- [ ] Bugfix
- [ ] Feature
- [x] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Tests related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior? :bar_chart:

Issue Number: N/A

There was no Pull Request template.

## What is the new behavior? :tada:

The PRs now automatically comes with the template, making it easier for everyone to understand the purpose of the PR.

## Does this introduce a breaking change? :gear:

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by flybayer** [comment]
Nice, thank you! I like this general idea. Looping @medelman17 in to comment on the specifics

**Comment by medelman17** [comment]
Thanks @ETLopes! I, too, like the general approach. And it looks great!! That said, we're still working on hammering out the specifics of our GitFlow processes, etc., which will definitely touch on a lot of the specifics above. So, I think we should table this PR for the time being. I don't anticipate that timeline being too long, and would be glad to take a revision to the template above at that time.

**Comment by flybayer** [comment]
This is the longest pending PR ever lol, but thank you @ETLopes!!

@all-contributors add @ETLopes for code

**Comment by flybayer** [comment]
@all-contributors add @ETLopes for code

**Pull request merged**
