### PR TITLE
#3813 Update recipes to work with blitz toolkit

### PR DESCRIPTION
**Pull request by siddhsuresh**
Closes: #3813 

Fixes
> Migrate over recipe functionality from legacy framework.
> 
> Some recipes still need to be updated to work with blitz 2.0 (#3813)

from #3784

### What are the changes and their implications?
- [x] updated export from ```transformBlitzConfig``` --> ```transformNextConfig``` in ```packages/blitz/src/installer/transforms/transform-next-config.ts```
- [x] updated the blitz imports in the recipe templates
- [x] moved the apps/pages directory to pages directory in few recipe templates to follow Nextjs file structure   
- [x] recipes/secureheaders
#### After
```js
// @ts-check

const withBundleAnalyzer = require("@next/bundle-analyzer")({
  enabled: process.env.ANALYZE === "true",
})
const { withBlitz } = require("@blitzjs/next")

/**
 * @type {import('@blitzjs/next').BlitzConfig}
 **/
const config = {
  reactStrictMode: true,

  headers: async () => {
    return [{
      key: "Strict-Transport-Security",
      value: "max-age=631138519"
    }, {
      key: "X-Frame-Options",
      value: "sameorigin"
    }, {
      key: "X-Content-Type-Options",
      value: "nosniff"
    }, {
      key: "Permissions-Policy",
      value: "default 'none'"
    }];
  },

  poweredByHeader: false
}

module.exports = withBlitz(withBundleAnalyzer(config))
```

image

 - [x]  recipes/theme-ui

image

 - [x]  recipes/vanilla-extract
 
image

### CODE REVIEW

**Comment by dillonraphael** [comment]
Hey @siddhsuresh this is great and really helpful. I've been battling with getting the CI to work the past few days. Do you have any idea why it fails randomly some times? Though you seem to have it working.

**Comment by siddhsuresh** [comment]
> Hey @siddhsuresh this is great and really helpful. I've been battling with getting the CI to work the past few days. Do you have any idea why it fails randomly some times? Though you seem to have it working.

Hey, @dillonraphael thanks!!. 

Regarding the CI fails, the most common error I encounter is the ```ELIFECYCLE  Test failed. See above for more details.``` even though the tests are passing locally and in my fork. 

So, usually what I do to fix the just to create a cosmetic commit (like in my latest commit I had just run prettier in the ```recipes/ghost/index.ts``` file), in order to run the CI with the updated cache of all the previous tests so that only the remaining test will run, which usually gets the CI to pass. 

But this is more of a hack than a method 😅

**Comment by dillonraphael** [comment]
> > Hey @siddhsuresh this is great and really helpful. I've been battling with getting the CI to work the past few days. Do you have any idea why it fails randomly some times? Though you seem to have it working.
> 
> Hey, @dillonraphael thanks!
> 
> Regarding the CI fails, the most common error I encounter is the `ELIFECYCLE  Test failed. See above for more details.` even though the tests are passing locally and in my fork.
> 
> So, usually what I do to fix this is to just create a cosmetic commit (like in my latest commit I had just run prettier in the `recipes/ghost/index.ts` file), in order to run the CI with the updated cache (created artefacts from the previous run) of all the previous tests so that only the remaining tests will run, which usually gets the CI to pass.
> 
> But this is more of a hack than a method 😅

I feel this is cumbersome. Maybe we should consider removing the cache?

**Comment by siddhsuresh** [comment]
> > > Hey @siddhsuresh this is great and really helpful. I've been battling with getting the CI to work the past few days. Do you have any idea why it fails randomly some times? Though you seem to have it working.
> > 
> > 
> > Hey, @dillonraphael thanks!
> > Regarding the CI fails, the most common error I encounter is the `ELIFECYCLE  Test failed. See above for more details.` even though the tests are passing locally and in my fork.
> > So, usually what I do to fix this is to just create a cosmetic commit (like in my latest commit I had just run prettier in the `recipes/ghost/index.ts` file), in order to run the CI with the updated cache (created artefacts from the previous run) of all the previous tests so that only the remaining tests will run, which usually gets the CI to pass.
> > But this is more of a hack than a method 😅
> 
> I feel this is cumbersome. Maybe we should consider removing the cache?



> > > Hey @siddhsuresh this is great and really helpful. I've been battling with getting the CI to work the past few days. Do you have any idea why it fails randomly some times? Though you seem to have it working.
> > 
> > 
> > Hey, @dillonraphael thanks!
> > Regarding the CI fails, the most common error I encounter is the `ELIFECYCLE  Test failed. See above for more details.` even though the tests are passing locally and in my fork.
> > So, usually what I do to fix this is to just create a cosmetic commit (like in my latest commit I had just run prettier in the `recipes/ghost/index.ts` file), in order to run the CI with the updated cache (created artefacts from the previous run) of all the previous tests so that only the remaining tests will run, which usually gets the CI to pass.
> > But this is more of a hack than a method 😅
> 
> I feel this is cumbersome. Maybe we should consider removing the cache?

@dillonraphael I agree that it is cumbersome, but ig the problem shouldn't lie with the caching as it is using an in-built feature of the turbo monorepo. But, I guess it wouldn't hurt trying to run the CI without the cache. I shall try it out in my fork and see.

**Comment by siddhsuresh** [comment]
@dillonraphael Ig the caching is not the problem I got all the test passing after 2 tries in https://github.com/siddhsuresh/blitz/pull/36.

**Comment by siddhsuresh** [comment]
Hey, @dillonraphael I got the CI working by splitting the testing into the two categories of tests in the repo, i.e. the unit tests in the ```./packages``` directory and the integration tests in the ```./integration-tests``` directory.  
Using the filter argument in the turbo CLI https://turborepo.org/docs/core-concepts/filtering to get this working.
Let me know if it is working in your end or any other changes should be made.

**Comment by dillonraphael** [comment]
Hey @siddhsuresh this PR is good to go. Just need to resolve the conflicts.

**Comment by siddhsuresh** [comment]
Updated the secure-headers recipe to fit the latest next.js convention, taking inspiration from https://github.com/blitz-js/blitz/pull/3177

**Comment by siddhsuresh** [comment]
@dillonraphael should I change the base branch to ```main``` or it is better to merge to the ```migrate-recipe``` PR?

**Comment by robodove** [comment]
when can we expect recipes to land in v2?

**Comment by beerose** [comment]
> when can we expect recipes to land in v2?

Should be in a few days :) We have a PR and it's been approved and ready to merge.

**Comment by robodove** [comment]
> > when can we expect recipes to land in v2?
> 
> 
> 
> Should be in a few days :) We have a PR and it's been approved and ready to merge.

but there won't be docs yet, i guess
the missing docs, especially for custom plugins, are holding back the ecosystem atm

**Pull request merged**
