### PR TITLE
Allow the `ctx` to be accessed within passport strategies

### PR DESCRIPTION
**Pull request by james2406**
Closes: https://github.com/blitz-js/blitz/issues/2052

### What are the changes and their implications?

This change allows access to the session inside the verify callback of the passport strategy.

### Checklist

- [ ] Changes covered by tests (tests added if needed)
- [x] PR submitted to [blitzjs.com](https://github.com/blitz-js/blitzjs.com) for any user facing changes

### CODE REVIEW

**Comment by james2406** [comment]
I tested this with the example auth project locally and it works as expected.

The only problem is, each strategy displays a typescript error whenever the `passportAuth` config is a callback. This is really strange because the config object types are the same for both the config object and config callback.

If you have any ideas why this could be happening, I'm happy to make the changes so this does not error!

Thanks

**Comment by flybayer** [comment]
wow that is weird 🤔 I tried a few things and couldn't get it to work either.

Also, you can go ahead and open a PR to the docs repo to document this

**Comment by flybayer** [comment]
For anyone else looking at this, do this:

1. `yarn`
2. `yarn dev`
3. Open `examples/auth/app/api/auth/[...auth].ts` and see the type error

**Comment by james2406** [comment]
> wow that is weird 🤔 I tried a few things and couldn't get it to work either.

Yeah. I'll give it another go tomorrow, but something tells me this could be a bug with typescript. It just doesn't make sense.

> Also, you can go ahead and open a PR to the docs repo to document this

Done! https://github.com/blitz-js/blitzjs.com/pull/399

**Comment by james2406** [comment]
Interesting. After a bit more investigation, I found the problem is the environment variables (whos types are guaranteed by the `assert` function) are reverting back to the type `string | undefined` once the callback is introduced.

I guess this makes sense as these variables could technically change.

The option would be to typecast:

```typescript
consumerKey: process.env.TWITTER_CONSUMER_KEY as string,
```

Or add something like an `environment.d.ts` file to the project which would contain the following:

```typescript
declare global {
  namespace NodeJS {
    interface ProcessEnv {
      TWITTER_CONSUMER_KEY: string;
      TWITTER_CONSUMER_SECRET: string;
    }
  }
}

export {};
```

**Comment by flybayer** [comment]
Sweet! Let's go with the `as string` approach because it's more copy-pastable and will prevent people from running into this (hopefully).

And let's add that type cast to the docs to, or at least mention it somehow there

**Comment by james2406** [comment]
> the `as string` approach because it's more copy-pastable

Yeah, it's a good point. I also thought the environment.d.ts file approach could confuse people if they are copy and pasting.

> And let's add that type cast to the docs to, or at least mention it somehow there

Will do.

**Pull request merged**
