### PR TITLE
upgrade internal typescript version

### PR DESCRIPTION
**Pull request by flybayer**
### What are the changes and their implications?

upgrade internal typescript version

### CODE REVIEW

**Comment by flybayer** [comment]
Houston we have a problem.

In `packages/core/src/auth/auth-types.ts` we do this trick so that user's can extend built in types:

```ts
export interface Session {
  // isAuthorize can be injected here
  // PublicData can be injected here
}

export type PublicData = "PublicData" extends keyof Session
  ? Session["PublicData"]
  : {userId: unknown}
```

This worked great until this attempt to upgrade 4.1 to 4.3. Now we get this build error:

```
packages/core/src/auth/auth-types.ts:18:13 - error TS2538: Type '"PublicData"' cannot be used as an index type.

18   ? Session["PublicData"]
```

Note: I've tested TS 4.3 in a normal blitz app and it works fine. The only issue is this type error in our internal typecheck step.

**Comment by flybayer** [comment]
I'm also getting this new error too:

```ts
packages/core/src/server/resolver.ts:295:50 - error TS2589: Type instantiation is excessively deep and possibly infinite.

295   zod<Schema extends ZodSchema<any, any>, Type = zInfer<Schema>>(schema: Schema) {
```

**Comment by JuanM04** [comment]
> I'm also getting this new error too:
> 
> ```ts
> packages/core/src/server/resolver.ts:295:50 - error TS2589: Type instantiation is excessively deep and possibly infinite.
> 
> 295   zod<Schema extends ZodSchema<any, any>, Type = zInfer<Schema>>(schema: Schema) {
> ```

Try upgrading Zod to v3.2 ([zod issue](https://github.com/colinhacks/zod/issues/473#issuecomment-860144275))

**Comment by flybayer** [comment]
@JuanM04 we already have that version installed

**Comment by JuanM04** [comment]
Try changing this:

```ts
import type {input as zInput, output as zOutput, ZodSchema} from "zod"

// ...

  zod<Schema extends ZodSchema<any, any>, InputType = zInput<Schema>, OutputType = zOutput<Schema>>(schema: Schema) {
    return (input: InputType): OutputType => schema.parse(input)
  },
```

Zod has a `z.input` and a `z.output` method because they can be different. Maybe that solves the issue

**Comment by flybayer** [comment]
Superseded by https://github.com/blitz-js/blitz/pull/2669

**Pull request closed without merging**
