### PR TITLE
Change all user facing references of next.js to blitz.js

### PR DESCRIPTION
**Pull request by ashikka**
Closes: #2434

### CODE REVIEW

**Comment by NamamiShanker** [comment]
Maybe you should also refactor the file names accordingly. You still have files named like next-build.ts, next-dev.ts etc. What do you say, @flybayer?

**Review by NamamiShanker — COMMENTED** [review]
For the files like `next-build.ts, next-dev.ts, next-export.ts...` etc, wouldn't it make more sense to rename them to `blitz-build.ts, blitz-dev.ts, blitz-export.ts...` and refactor the code accordingly?

**Comment by ashikka** [comment]
> For the files like `next-build.ts, next-dev.ts, next-export.ts...` etc, wouldn't it make more sense to rename them to `blitz-build.ts, blitz-dev.ts, blitz-export.ts...` and refactor the code accordingly?

For now, the issues raised only mentioned to change error messages and help texts and specifically asked for not changing anything else. I guess we should wait for @flybayer to reply.

**Comment by flybayer** [comment]
> For the files like `next-build.ts, next-dev.ts, next-export.ts...` etc, wouldn't it make more sense to rename them to `blitz-build.ts, blitz-dev.ts, blitz-export.ts...` and refactor the code accordingly?

No, we must keep original file names in order to minimize merge conflicts when updating our fork from next.js upstream

**Comment by flybayer** [comment]
Thanks @ashikka! There will be a number of tests fail which test the string output. Probably faster for you to search through `nextjs/test/` and update references there than searching through all the failed tests.

**Comment by ashikka** [comment]
> Thanks @ashikka! There will be a number of tests fail which test the string output. Probably faster for you to search through `nextjs/test/` and update references there than searching through all the failed tests.

Alright! Will do.

**Comment by flybayer** [comment]
Oh, also there's a bunch of links to "nextjs.org" that need updated to the appropriate page on blitzjs.com

**Comment by ashikka** [comment]
> Oh, also there's a bunch of links to "nextjs.org" that need updated to the appropriate page on blitzjs.com

Yup, I saw that. WIll get to it.

**Comment by markhughes** [comment]
@flybayer does this mean we'll need to setup some new documentation for the links from errors:
- https://nextjs.org/docs/messages/google-font-display
- https://nextjs.org/docs/messages/google-font-preconnect
- https://nextjs.org/docs/messages/link-passhref
- https://nextjs.org/docs/messages/no-unwanted-polyfillio
- https://nextjs.org/docs/messages/no-title-in-document-head
- .. etc

**Comment by ashikka** [comment]
> Thanks @ashikka! There will be a number of tests fail which test the string output. Probably faster for you to search through `nextjs/test/` and update references there than searching through all the failed tests.

Hey @flybayer! I pushed some new commits, can you approve the workflow?

**Comment by flybayer** [comment]
> @flybayer does this mean we'll need to setup some new documentation for the links from errors:
> 
> * [nextjs.org/docs/messages/google-font-display](https://nextjs.org/docs/messages/google-font-display)
> * [nextjs.org/docs/messages/google-font-preconnect](https://nextjs.org/docs/messages/google-font-preconnect)
> * [nextjs.org/docs/messages/link-passhref](https://nextjs.org/docs/messages/link-passhref)
> * [nextjs.org/docs/messages/no-unwanted-polyfillio](https://nextjs.org/docs/messages/no-unwanted-polyfillio)
> * [nextjs.org/docs/messages/no-title-in-document-head](https://nextjs.org/docs/messages/no-title-in-document-head)
> * .. etc

Yes probably, but let's leave these for now and address is separately

**Comment by flybayer** [comment]
> Hey @flybayer! I pushed some new commits, can you approve the workflow?

Done! I've also just invited you to have write access to these repos, so shouldn't need CI approval once you accept that :)

**Review by NamamiShanker — DISMISSED** [review]

**Comment by flybayer** [comment]
Hey @ashikka, I'd like to get this in the next release, so I can finish it if you can't get to it by today or tomorrow

**Comment by ashikka** [comment]
> Hey @ashikka, I'd like to get this in the next release, so I can finish it if you can't get to it by today or tomorrow

Yup! Go ahead please.

**Pull request merged**
