### PR TITLE
Revert "#3775 Only generate prisma client if it has not been generated"

### PR DESCRIPTION
**Pull request by dillonraphael**
Reverts blitz-js/blitz#3780

### CODE REVIEW

**Comment by siddhsuresh** [comment]
Hey, @dillonraphael was there some error in #3780?

**Comment by dillonraphael** [comment]
> Hey, @dillonraphael was there some error in #3780?

Unfortunately after we thought about it, there are a couple edge cases where this solution wouldn't work.

1. The user's schema may not always be in the `db` directory. There is a possibility of having it in a monorepo
2. It doesn't account for which blitz project. For example, the user may have 2 blitz projects locally on their machine

**Comment by siddhsuresh** [comment]
> > Hey, @dillonraphael was there some error in #3780?
> 
> @siddhsuresh Unfortunately after we thought about it, there are a couple edge cases where this solution wouldn't work.
> 
> 1. The user's schema may not always be in the `db` directory. There is a possibility of having it in a monorepo
> 2. It doesn't account for which blitz project. For example, the user may have 2 blitz projects locally on their machine

Oh, I had not considered the first case while creating the solution, while ig for the second case I think my solution takes care of the identification of the blitzjs project by taking the creation time of the current directory into account which should not be the same for any two projects

**Comment by dillonraphael** [comment]
Decided not to revert, and build off what @siddhsuresh contributed (which I'm extremely grateful for). I'll close this PR and share the issue for simplifying the solution. https://github.com/blitz-js/blitz/issues/3801

**Pull request closed without merging**
