### PR TITLE
CI Fixes

### PR DESCRIPTION
**Pull request by dillonraphael**
This PR updates the `test-utils` to export functions that also spawns blitz commands.
- `runBlitzCommand(argv, options)`
- `runBlitzCommandDev(argv, stdOut, opts)`
- `blitzLaunchApp(port, opts)`
- `blitzStart(port, opts)`

### CODE REVIEW

**Comment by dillonraphael** [comment]
@siddhsuresh some more updates for the CI incase you're interested

**Comment by siddhsuresh** [comment]
> @siddhsuresh some more updates for the CI incase you're interested

Hey, @dillonraphael are there any updates to be made by me? 

and a redundant folder in ```integration-tests/rpc/undefined``` has been added to the PR, and a temp file ```integration-tests/auth/blitz-1662766277443.6956-prisma-client.json``` has also crept into the commit.  

Ig it is safe to remove them, as I have removed them and re-run the test in https://github.com/siddhsuresh/blitz/pull/50 with all passing.

Those files are causes the file difference in the PR to become +22,500!!

**Comment by siddhsuresh** [comment]
@dillonraphael I am not able to make a suggestion in the review part for these line as they are not near the changed parts.

https://github.com/blitz-js/blitz/blob/45eef9e3de124cd77af3eb9dc92fc0a4f7166f81/.github/workflows/main.yml#L131

The line can be changed to the following
```
folders=$(tree -J -d -L 1 | jq -c  '.[0].contents | map(.name | tostring)'| jq 'del(.[] | select(. == "utils"))')
```
The excludes the utils file in integration-tests directory as there are no tests written in them

**Comment by siddhsuresh** [comment]
@dillonraphael I am not able to make a suggestion in the review part for these line as they are not near the changed parts.

https://github.com/blitz-js/blitz/blob/45eef9e3de124cd77af3eb9dc92fc0a4f7166f81/.github/workflows/main.yml#L131

The line can be changed to the following
```bash
tree -J -d -L 1 | jq -c  '.[0].contents | map(.name | tostring) | map(select(. != "utils"))'
folders = $(tree -J -d -L 1 | jq -c  '.[0].contents | map(.name | tostring) | map(select(. != "utils"))')
```
The excludes the ```utils``` file in ```integration-tests``` directory as there are no tests written in them

**Comment by dillonraphael** [comment]
> @dillonraphael I am not able to make a suggestion in the review part for these lines as they are not near the changed lines in this PR.
> 
> > I can submit a PR to this branch with these changes if you want
> 
> https://github.com/blitz-js/blitz/blob/45eef9e3de124cd77af3eb9dc92fc0a4f7166f81/.github/workflows/main.yml#L130-L131
> 
> These lines can be changed to the following
> 
> ```shell
> tree -J -d -L 1 | jq -c  '.[0].contents | map(.name | tostring) | map(select(. != "utils"))'
> folders = $(tree -J -d -L 1 | jq -c  '.[0].contents | map(.name | tostring) | map(select(. != "utils"))')
> ```
> 
> The excludes the `utils` file in `integration-tests` directory as there are no tests written in them GitHub Action: https://github.com/siddhsuresh/blitz/actions/runs/3050539581

Thanks for this @siddhsuresh. I will add.

**Review by beerose — APPROVED** [review]
👏

**Pull request merged**
