### PR TITLE
Prevent using Reserved Keywords in `generate` command

### PR DESCRIPTION
**Pull request by mabadir**
Closes: #2380

### What are the changes and their implications?

Comparing model name against reserved keywords list.

## Bug Checklist

- [x] Unit test added

### CODE REVIEW

**Review by flybayer — COMMENTED** [review]
Thanks Mina! After reviewing this, I think it would actually be better to not have any reserved keywords.

Instead we just change the generated paths to accommodate. 

`blitz generate all page` -> generates to `app/page-model/`

Same for `api`, `query`, and `mutation`.

What do you think?

**Comment by mabadir** [comment]
Makes sense, that will impact our auto generated routes I assume?

**Comment by flybayer** [comment]
> Makes sense, that will impact our auto generated routes I assume?

Yes

**Comment by mabadir** [comment]
Considering, it's completely different approach, I am closing this PR and opening a new one.

**Pull request closed without merging**
