### PR TITLE
Added codemod support for legacy projects with a /src folder

### PR DESCRIPTION
**Pull request by Doc0x1**
### What are the changes and their implications?
Changes the codemod upgrade-legacy tool to add support for legacy projects which have folders nested inside a /src directory
## Bug Checklist

- [x] Changeset added (run `pnpm changeset` in the root directory)

## Feature Checklist

- [x] Changeset added (run `pnpm changeset` in the root directory)

### CODE REVIEW

**Review by siddhsuresh — COMMENTED** [review]
thanks for the PR @Doc0x1! this is a good start. 

1. https://github.com/blitz-js/blitz/blob/a09685a63a01a01b697047b3200427f12489b214/packages/codemod/src/upgrade-legacy.ts#L49

I feel the above line we should make the following change 
```diff
- const appDir = path.resolve("app")
+ const appDir = fs.existsSync(path.resolve("app")) ? fs.existsSync(path.resolve("src"))
```
since in this case the user has the files only in src directory and not in the app

2. https://github.com/blitz-js/blitz/blob/a09685a63a01a01b697047b3200427f12489b214/packages/codemod/src/upgrade-legacy.ts#L1317

we should use the same utility here.

other than these, looks good!

**Comment by Doc0x1** [comment]
Okay @siddhsuresh sounds good, I'll implement those changes once I'm back home

**Comment by Doc0x1** [comment]
@siddhsuresh Okay, should be good to go for review. Let me know if there's anything else. Also I decided to throw an Error around line 49 inside a try catch statement in the event that appDir is just an empty string to add a bit of error handling towards the start.

**Review by siddhsuresh — COMMENTED** [review]
LGTM!

**Review by siddhsuresh — APPROVED** [review]

**Pull request merged**
