### PR TITLE
Add initial CLI project

### PR DESCRIPTION
**Pull request by mabadir**
Initial PR for oclif CLI

### CODE REVIEW

**Comment by flybayer** [comment]
Awesome Mina, thank you! My only comment for now is that we should change the tests to use Jest instead of Mocha so all our tests use the same framework.

**Comment by flybayer** [comment]
Also, we should use the same tsconfig for everything as much as possible. I.e. use `"extends": "../../tsconfig.json"`.  Hopefully @medelman17 can help us get that sorted out.

**Comment by mabadir** [comment]
Awesome, thanks @flybayer for the review and comments, I push another PR.
Many thanks to Lorenzo for the support.

**Comment by flybayer** [comment]
Closing this — reopened as #8 with a native blitz repo branch

**Pull request closed without merging**
