### PR TITLE
Fix .gitignore files not being ignored by blitz

### PR DESCRIPTION
**Pull request by ntgussoni**
Closes: #940 

### What are the changes and their implications?
The current canary was indeed using the .gitignore to filter out unwanted folders and files, however it didn't take `.git/info/excludes` file into account.

This PR adds the necessary changes to parse all exclude files in the project, including any git submodule in the tree.

### Checklist

- [x] Tests added for changes
- [x] PR submitted to [blitzjs.com](https://github.com/blitz-js/blitzjs.com) for any user facing changes

### CODE REVIEW

**Comment by flybayer** [comment]
You haven't added support for global gitignore to this, yet, right?

**Comment by ntgussoni** [comment]
> You haven't added support for global gitignore to this, yet, right?

I have it on a branch, im adding some tests but i havent had the time this couple of days. I'll Try to push my changes soon

**Comment by flybayer** [comment]
Cool, no problem! Mark it back as ready for review when finished.

**Comment by ntgussoni** [comment]
@flybayer This should be enough for now. 

One thing to keep in mind is that you could have something like `history` in your .gitignore and git would ignore 
`history/foo/bar` as well.

Since we are piping these strings directly to a glob search, the glob would only match anything called `history` but not `history/**`.

For most cases we should be fine with what we have right now. But we could explore using `git check-ignore` instead of manually reading the files.

**Review by flybayer — APPROVED** [review]

**Comment by flybayer** [comment]
@ntgussoni awesome, thanks!! Will let @ryardley do final review.

@all-contributors add @ntgussoni for code

**Comment by flybayer** [comment]
@ryardley can you review this?

**Review by ryardley — APPROVED** [review]
Looks good to me

**Comment by flybayer** [comment]
@all-contributors add @ntgussoni for code

**Comment by flybayer** [comment]
@all-contributors add @ntgussoni for code

**Pull request merged**
