### PR TITLE
Add some tests to `@blitzjs/installer` (meta)

### PR DESCRIPTION
**Pull request by rembrandtreyes**
Closes: part of https://github.com/blitz-js/blitz/issues/466

### What are the changes and their implications?
Created tests for the executor file.
Added a `ink-testing-library` package to `@blitzjs/installer`

### Checklist

- [x] Tests added for changes
- [ ] PR submitted to [blitzjs.com](https://github.com/blitz-js/blitzjs.com) for any user facing changes

### CODE REVIEW

**Comment by flybayer** [comment]
Thank you @rembrandtreyes!

Any ideas why it's failing in CI?

```
@blitzjs/installer: FAIL test/executors/executor.test.tsx
@blitzjs/installer:   ● Executor › should render Frontmatter
@blitzjs/installer:     expect(received).toMatchSnapshot()
@blitzjs/installer:     Snapshot name: `Executor should render Frontmatter 1`
@blitzjs/installer:     - Snapshot  - 4
@blitzjs/installer:     + Received  + 4
@blitzjs/installer:       ↵
@blitzjs/installer:     - +––––––––––––––+
@blitzjs/installer:     - ⎪   New File   ⎪
@blitzjs/installer:     - +––––––––––––––+
@blitzjs/installer:     - Testing text for a new file
@blitzjs/installer:     + +––––––––––––––+
@blitzjs/installer:     + ⎪   New File   ⎪
@blitzjs/installer:     + +––––––––––––––+
@blitzjs/installer:     + Testing text for a new file
@blitzjs/installer:       ↵
```
I can't visually see anything different, maybe some trailing space or something?

I did just restart CI in case it was a one time fluke.

**Comment by rembrandtreyes** [comment]
> Thank you @rembrandtreyes!
> 
> Any ideas why it's failing in CI?
> 
> ```
> @blitzjs/installer: FAIL test/executors/executor.test.tsx
> @blitzjs/installer:   ● Executor › should render Frontmatter
> @blitzjs/installer:     expect(received).toMatchSnapshot()
> @blitzjs/installer:     Snapshot name: `Executor should render Frontmatter 1`
> @blitzjs/installer:     - Snapshot  - 4
> @blitzjs/installer:     + Received  + 4
> @blitzjs/installer:       ↵
> @blitzjs/installer:     - +––––––––––––––+
> @blitzjs/installer:     - ⎪   New File   ⎪
> @blitzjs/installer:     - +––––––––––––––+
> @blitzjs/installer:     - Testing text for a new file
> @blitzjs/installer:     + +––––––––––––––+
> @blitzjs/installer:     + ⎪   New File   ⎪
> @blitzjs/installer:     + +––––––––––––––+
> @blitzjs/installer:     + Testing text for a new file
> @blitzjs/installer:       ↵
> ```
> 
> I can't visually see anything different, maybe some trailing space or something?
> 
> I did just restart CI in case it was a one time fluke.

Hmm not sure exactly. I'll dig into this a bit more.

**Comment by rembrandtreyes** [comment]
Looks like GitHub actions run terminal commands without color, and the snapshots from ink components had color in them.

I updated the package.json for packages/installer to run without color.

**Comment by flybayer** [comment]
Sweeet, good catch!

**Comment by flybayer** [comment]
@all-contributors add @rembrandtreyes for test

**Pull request merged**
