### PR TITLE
Cypress test fix

### PR DESCRIPTION
**Pull request by benediktms**
Closes: #1368

### What are the changes and their implications?
Changed the spelling of 'Log In' to 'Login' on the initially generated forms and the Cypress tests so they pass when a user first runs them.

This does not address any issues with the session test (which did not work for me). 

### Checklist

- [ ] Tests added for changes
- [ ] ~PR submitted to [blitzjs.com](https://github.com/blitz-js/blitzjs.com) for any user facing changes~

### CODE REVIEW

**Comment by flybayer** [comment]
@benediktms well, somehow your changes are causing a failing test in the auth example. At first I thought it wasn't related to your changes, but now I know for sure it is.

Can you investigate and fix?

Thanks!

**Comment by benediktms** [comment]
@flybayer I'll dive into it again tonight and report back

**Comment by benediktms** [comment]
@flybayer Sorry that it took a bit longer! I'm trying to test a fix now, but I'm a bit nervous about resolving the dependency conflicts, but I saw there is a depfu PR to bump the prisma dependencies to 2.10. Shall I keep dependencies on 2.9 on this branch for botht the cli and the client?

**Comment by flybayer** [comment]
@benediktms that PR is merged now, so should be able to resolve the conflicts by using what's on canary.

**Comment by benediktms** [comment]
@flybayer awesome merged that in now, is there anything else I need to take into account for CI to start running tests?

**Comment by flybayer** [comment]
Sweet, thanks!

@all-contributors add @benediktms for code

**Pull request merged**
