### PR TITLE
In-memory FS for tests

### PR DESCRIPTION
**Pull request by dajinchu**
### Type: tests

Closes: #179 

### What are the changes and their implications? :gear:

Using `mock-fs` to mock the file system. Entire fixtures folder is deleted and mock files are specified on a per-test basis. `mock-fs` mocks out all uses of fs, so `resolveBinAsync` no longer works, since there is no node_modules in the mock file system. Added a mock for it as well.

### Checklist

- [ ] Tests added for changes
- [ ] Any added terminal logging uses `packages/server/src/log.ts`

### CODE REVIEW

**Comment by dajinchu** [comment]
These tests actually exposed a real bug as shown by test case `dev > when with next.config > should fail when passed a next.config.js` where we don't log to console when there's a next.config.js, we just throw and exit. The test is skipped for now as its failure causes other tests not to run.

**Comment by ryardley** [comment]
> These tests actually exposed a real bug as shown by test case dev > when with next.config > should fail when passed a next.config.js where we don't log to console when there's a next.config.js, we just throw and exit. The test is skipped for now as its failure causes other tests not to run.

Yep this needs refactoring. I will have a go at fixing this up today.

**Comment by flybayer** [comment]
@all-contributors add @dajinchu for code

**Comment by wKovacs64** [comment]
Yeah so this change doesn't work in Windows. 😔 I'll open a new issue with details.

**Pull request merged**
