### PR TITLE
Allow using Route Manifest for `Page.redirectAuthenticatedTo`

### PR DESCRIPTION
**Pull request by Skn0tt**
### What are the changes and their implications?

Allow devs to use Url Object for `redirectAuthenticatedTo`

```diff
- LoginPage.redirectAuthenticatedTo = Routes.DashboardPage().pathname
+ LoginPage.redirectAuthenticatedTo = Routes.DashboardPage()
```

## Bug Checklist

- [ ] Integration test added (see [test docs](https://blitzjs.com/docs/contributing#running-tests) if needed)

## Feature Checklist

- [ ] Integration test added (see [test docs](https://blitzjs.com/docs/contributing#running-tests) if needed)
- [ ] Documentation added/updated (submit PR to [blitzjs.com repo](https://github.com/blitz-js/blitzjs.com))

### CODE REVIEW

**Comment by Skn0tt** [comment]
cc #2231

**Comment by flybayer** [comment]
Thanks @Skn0tt! Can you update our docs to include this feature?

**Comment by erikshestopal** [comment]
@Skn0tt I have some routes that require query params from a session for example in order to redirect. Is this currently possible? 

```tsx
// ideal state
Page.redirectedAuthenticatedTo = (session: Session) => Routes.TeamPage({ slug: session.teamName })
```

cc @flybayer

**Comment by Skn0tt** [comment]
Not at the moment, but I guess it should be possible. WDYT @flybayer?

**Comment by flybayer** [comment]
I think that should work. We just have to make sure we account for the fact that session is empty on first render.

**Pull request merged**
