### PR TITLE
Fix Routes manifest for pages with parent & child relationships (patch)

### PR DESCRIPTION
**Pull request by frankiesardo**
Closes: #2407

### CODE REVIEW

**Comment by flybayer** [comment]
Thanks @frankiesardo! Next time please leave the PR template in place :)

**Review by flybayer — APPROVED** [review]

**Comment by flybayer** [comment]
@frankiesardo you have a failing test:

```
[@blitzjs/server::jest] FAIL src/stages/route-import-manifest/route-import-manifest.test.ts
[@blitzjs/server::jest]   ● generateManifest
[@blitzjs/server::jest] 
[@blitzjs/server::jest]     expect(received).toEqual(expected) // deep equality
[@blitzjs/server::jest] 
[@blitzjs/server::jest]     - Expected  - 2
[@blitzjs/server::jest]     + Received  + 2
[@blitzjs/server::jest] 
[@blitzjs/server::jest]     @@ -2,12 +2,12 @@
[@blitzjs/server::jest]         "declaration": "import type { ParsedUrlQueryInput } from \"querystring\"
[@blitzjs/server::jest]       import type { RouteUrlObject } from \"blitz\"
[@blitzjs/server::jest] 
[@blitzjs/server::jest]       export const Routes: {
[@blitzjs/server::jest]         Home(query?: ParsedUrlQueryInput): RouteUrlObject;
[@blitzjs/server::jest]     -   CommentView(query: { postId: string | number; openedCommentPath: (string | number)[] } & ParsedUrlQueryInput): RouteUrlObject;
[@blitzjs/server::jest]     -   UserProfileView(query: { userId: string | number; openedPhotoId?: (string | number)[] } & ParsedUrlQueryInput): RouteUrlObject;
[@blitzjs/server::jest]     +   CommentView(query: { postId: string | number | undefined; openedCommentPath: (string | number | undefined)[] } & ParsedUrlQueryInput): RouteUrlObject;
[@blitzjs/server::jest]     +   UserProfileView(query: { userId: string | number | undefined; openedPhotoId?: (string | number | undefined)[] } & ParsedUrlQueryInput): RouteUrlObject;
[@blitzjs/server::jest]       }",
[@blitzjs/server::jest]         "implementation": "exports.Routes = {
[@blitzjs/server::jest]         Home: (query) => ({ pathname: \"home/\", query }),
[@blitzjs/server::jest]         CommentView: (query) => ({ pathname: \"posts/[postId]/[...openedCommentPath]\", query }),
[@blitzjs/server::jest]         UserProfileView: (query) => ({ pathname: \"users/[userId]/[[...openedPhotoId]]\", query })
[@blitzjs/server::jest] 
[@blitzjs/server::jest]       90 |       },
[@blitzjs/server::jest]       91 |     }),
[@blitzjs/server::jest]     > 92 |   ).toEqual({
[@blitzjs/server::jest]          |     ^
[@blitzjs/server::jest]       93 |     implementation: `
[@blitzjs/server::jest]       94 | exports.Routes = {
[@blitzjs/server::jest]       95 |   Home: (query) => ({ pathname: "home/", query }),
[@blitzjs/server::jest] 
[@blitzjs/server::jest]       at Object.<anonymous> (src/stages/route-import-manifest/route-import-manifest.test.ts:92:5)
```

Locally run `yarn test` inside `packages/server/` and you'll see the error. Let me know once you fix it

**Comment by Skn0tt** [comment]
I don't think it's a good idea to change the signature of the Route Manifest. Why would one of these paths take `undefined`? If they were actually passed `undefined`, it'd break.

The better fix here would be to update the generator to emit `projectId!` instead of `projectId`, or `useParam(...)!`.

**Review by Skn0tt — CHANGES_REQUESTED** [review]
See comment above

**Comment by frankiesardo** [comment]
@Skn0tt I can push a change that adds `!` to `const __parentModelId__ = useParam("__parentModelId__", "number")!` if that works ok with you?

**Review by Skn0tt — CHANGES_REQUESTED** [review]
Yes, that works @frankiesardo!
One minor thing: `useParam` actually returns `undefined` while generating the static site templates, because there are no parameters available at build time. So placing the `!` after `useParam` may confuse devs.
I think we can fix this by placing the `!` where they're used as links. I'll push a commit real quick :D

**Comment by Skn0tt** [comment]
I can't push to this PR for some reason. Here's the commit: https://github.com/blitz-js/blitz/commit/f8e947e481215d519529d9d12c4464ffce765337

**Comment by frankiesardo** [comment]
Yeah makes sense 👍 I've copied that and I've also covered the /new endpoints too

**Review by flybayer — APPROVED** [review]
Thank you!!

**Pull request merged**
