### PR TITLE
Add Jest and React Testing Library to new apps

### PR DESCRIPTION
**Pull request by peaonunes**
Closes: #277

### What are the changes and their implications?

Adds jest and RTL setup and an example test. The setup is very inspired on what `create-react-app` setups by default with fewer configurations on the config file.

I've added both `jest` which is the test runner and the [`react-testing-library`](https://testing-library.com/) which is the default and recommended approach to write tests by the `create-react-app`.

image

### Checklist

- [ ] Tests added for changes
- [x] PR submitted to [blitzjs.com](https://github.com/blitz-js/blitzjs.com) for any user facing changes

### CODE REVIEW

**Comment by peaonunes** [comment]
I still need to test it in the generate app, I've just tested inside the `app` folder 😄

**Comment by flybayer** [comment]
@peaonunes awesome, thank you!! I'm SO sorry I'm so late replying to this. I traveled from Thailand to the US this week and still am getting caught up.

I'm trying to get a new stable blitz release out the door asap from what we have on canary. I'll come back and review this asap, probably within a few days.

**Comment by peaonunes** [comment]
> @peaonunes awesome, thank you!! I'm SO sorry I'm so late replying to this. I traveled from Thailand to the US this week and still am getting caught up.
> 
> I'm trying to get a new stable blitz release out the door asap from what we have on canary. I'll come back and review this asap, probably within a few days.

No worries mate, I knew that hahah! Hope you are setting down well there.

Take your time, the release is probably more important 😄 🚀

**Comment by peaonunes** [comment]
Hey @aem , good point you made. Although that level of tests out of the box is not common we can definitely do that if we are opinionated about how good test looks like. I would do that in a different PR though because I think this one already adds some value which is the test setup (we have none so far). That way, while users start benefiting on the test setup we work on putting toghether tests that cover more behaviour of our generated code. What do you think?

**Comment by merelinguist** [comment]
@peaonunes I agree, that should come in a second PR.

**Comment by flybayer** [comment]
@aem I was wanting to review this before merging since it directly affects UX, But it's ok, I'll come back and review asap. Any changes can be addressed in another PR.

**Comment by aem** [comment]
oops, sorry about that!

**Comment by peaonunes** [comment]
@flybayer do we have any step-by-step review doc? We could add it or a link to it in the PR description. I do not know if that would be redundant because I understand you want to double check the changes, but that's an idea.

Let me know if you find any issue, we can revert the merge and fix that.

**Comment by flybayer** [comment]
Alright everyone, I've opened a follow up PR which finishes up the default jest integration: https://github.com/blitz-js/blitz/pull/847

Please review.

@peaonunes and now, we don't except for the PR template checklist and required review by code owners. I'll add myself as a code owner of the new app template.

**Pull request merged**
