### PR TITLE
🚀 Add context path option to `blitz generate`

### PR DESCRIPTION
**Pull request by aem**
### Type: feature

Closes: https://github.com/blitz-js/blitz/issues/232

### What are the changes and their implications? :gear:

Adds a new CLI flag to support contextual file generation. Both Windows and UNIX paths are accepted, and you can pass the context in the model name rather than using the CLI flag if you'd like. That means all of the following are valid commands on any operating system:

* `blitz generate queries admin/tasks/todos`
* `blitz generate queries admin\tasks\todos`
* `blitz generate queries todos --context=admin/tasks`
* `blitz generate queries todos --context=admin\tasks`

All 4 of those output the exact same files - `app/admin/tasks/todos/queries/getTodo(s).ts`

### Checklist

- [x] Tests added for changes
- [x] Any added terminal logging uses `packages/server/src/log.ts`

### CODE REVIEW

**Comment by flybayer** [comment]
Looks great! But fails for `admin\tasks`. I committed a failing tests to this branch.

```
~/c/b/e/store> blitz g all admin\pizza -d
You are using alpha software - if you have any problems, please open an issue here:
  https://github.com/blitz-js/blitz/issues/new/choose

Would create    app/adminpizzas/pages/adminpizzas/[id]/edit.tsx
Would create    app/adminpizzas/pages/adminpizzas/[id].tsx
Would create    app/adminpizzas/pages/adminpizzas/index.tsx
Would create    app/adminpizzas/pages/adminpizzas/new.tsx
Would create    app/adminpizzas/queries/getAdminpizza.ts
Would create    app/adminpizzas/queries/getAdminpizzas.ts
Would create    app/adminpizzas/mutations/createAdminpizza.ts
Would create    app/adminpizzas/mutations/deleteAdminpizza.ts
Would create    app/adminpizzas/mutations/updateAdminpizza.ts
```

**Comment by aem** [comment]
@flybayer it seems like the test you committed will never pass on unix-based systems. any POSIX-compliant shell will escape the \t before it even gets into the node context. the last test in the suite that has the escaped `\` characters is correctly testing the windows behavior since the string we're operating on has the slashes in it, but the test with a single slash is testing how the script handles a context path of `admin    asks`. I think it makes sense to revert that test and merge as is

**Comment by aem** [comment]
here's a contrived example in node of how JS handles this - 
```
> node
Welcome to Node.js v12.16.3.
Type ".help" for more information.
> let a = '\t'
undefined
> for (let i = 0; i < a.length; i++) {
... console.log(a[i]);
... }

undefined
> 
```

**Comment by flybayer** [comment]
Ok that makes sense! I was just going off what you said in the first post:

>  That means all of the following are valid commands on any operating system:

**Comment by aem** [comment]
@flybayer yeah my wording was incorrect there, backslashes will only work on windows. having said that, i don’t expect that to be an issue, i assume anyone on mac/linux is using forward slashes

**Pull request merged**
