### PR TITLE
Add base infrastructure for `blitz install`

### PR DESCRIPTION
**Pull request by aem**
### Type: Feature

Related: https://github.com/blitz-js/blitz/issues/242

### What are the changes and their implications? :gear:

This PR adds the infrastructure and initial implementation for Blitz installers. The installer framework allows us to write a declarative set of steps to install third-party dependencies into a Blitz application.

This version is missing a few key features that we'll need for a public release so it's still hidden from the CLI. The goal is to get the MVP in here, and we can iterate and continue to implement features after this.

 🚨 **Before reviewing, your question may be answered by an unimplemented feature!** 🚨

#### Known unimplemented or not-working features

Ordered from most important to least

1. **Remote installer execution.** Currently I only support local file paths. We should support "native" installers built by us at `github.com/blitz-js/installers` by just a name (e.g. `blitz install tailwindcss`), or by an arbitrary GitHub URL as well (e.g. `https://github.com/aem/my-custom-blitz-installer`). Both of these should download the repo's source as a tarball, extract the proper directory into a temp directory, and then import it as the installer. Next.js examples do this, so we should be able to take inspiration from their implementation.
2. **Proper npm version resolution for `AddDependencyExecutor`.** Currently I just blindly pass the arguments into `yarn`/`npm` `add`. We should use similar logic to what we use in the app generator to resolve the latest valid version and pin it
3. **Transforms that target multiple files.** I put a placeholder field `selectTargetFiles` to allow an installer author to dynamically select multiple files to transform rather than a single target. I don't really know what we want this UX to look like so I left it unimplemented for now.
4. **Maybe a dry-run mode for the transform executor?** This one isn't a must-have for me but might be nice to add.
5. **Write up some consumable docs on `recast`.** We might not need them if our library of default transforms is extensive enough, but we won't really know that until we release this more widely.

### Checklist

- [ ] Tests added for changes
- [ ] Any added terminal logging uses `packages/server/src/log.ts`

### CODE REVIEW

**Comment by aem** [comment]
To test the installer, you can use this custom installer i've already built:

1. `yarn && yarn build`
2. `cd examples`
3. `blitz new installer-test`
4. `cd installer-test`
5. `git clone git@github.com:aem/sample-blitz-tailwind-installer.git`
6. `blitz install ./sample-blitz-tailwind-installer/index.ts`

**Comment by merelinguist** [comment]
Tried this locally and it’s amazing!

**Comment by wKovacs64** [comment]
sick.

**Comment by aem** [comment]
> We could just add the tailwind installer to the installer package for now, just to get it to work with blitz install tailwind.

Definitely. Remote installer support is the first thing on my list to tackle once this gets in

> When do you expect it could be merged?

It's ready now! Once I add the dep to the `blitz` package we should be all set. The command is hidden in the CLI right now so we can merge and publish future releases without exposing this to users until we're ready.

**Pull request merged**
