### PR TITLE
Route manifest replace nbsp with normal space

### PR DESCRIPTION
**Pull request by esemeniuc**
Closes: None

## Bug Checklist

- [ ] Integration test added (see [test docs](https://blitzjs.com/docs/contributing#running-tests) if needed)

## Feature Checklist

- [ ] Integration test added (see [test docs](https://blitzjs.com/docs/contributing#running-tests) if needed)
- [ ] Documentation added/updated (submit PR to [blitzjs.com repo](https://github.com/blitz-js/blitzjs.com))

### CODE REVIEW

**Comment by flybayer** [comment]
@esemeniuc thank you!! You have a failing test because you need to update the snapshot test for this

**Comment by flybayer** [comment]
@esemeniuc are you able to fix the test? :)

**Comment by esemeniuc** [comment]
re-running now

**Comment by flybayer** [comment]
@esemeniuc you merged in canary, but didn't update the test file. But I just pushed a commit that fixed it.

**Comment by esemeniuc** [comment]
Sorry I missed that! I see the file diff now, thank you :)

**Pull request merged**
