### PR TITLE
feat(cli): blitz generate command

### PR DESCRIPTION
**Pull request by marcoseoane**
## blitz generate

`blitz generate context/entity` produces the following folder structure plus the respective files

```
context/
-- entity/
---- pages/
    ContextEntityController.js
    ContextEntityModel.js
```

Nested file structures are also supported, with the prefix on the entity file names always being the preceding directory as seen in the next example:

`blitz generate context/nestedContext/entity`

Will generate the structure below

```
context/
-- nestedContext/
---- entity/
------ pages/
      NestedContextEntityController.js
      NestedContextEntityModel.js
```
And finally just providing an entity name will give you

```
entity/
-- pages/
  EntityController.js
  EntityModel.js
  ```
  (although I have spotted an error with the current code that puts the entity name in filenames twice, so will have to push a fix for this)
##
One design decision I have put into the code which I want everyone to give their thoughts on is the formatting of the top level context directory name. 
Currently the code is setting it to be lowercase, so if we take the `context/nestedContext` example and change `context` to be `Context`... the directory structure will come out looking like `context/nestedContext`. 

I took this direction with the idea that it would be nice to keep the display/formatting of all the root level directories in the blitz app cohesive, anything nested deeper will be up to the developer.

Next step will be setting up the template for the `Model` files, and any other default files we would like to include as the result of `generate`

### CODE REVIEW

**Comment by flybayer** [comment]
Are you wanting to PR this into `canary` or into @lorenzorapetti's `custom-generator` ? 

If into canary, I think we should wait to merge this until #25 is merged, right?

**Comment by marcoseoane** [comment]
> Are you wanting to PR this into `canary` or into @lorenzorapetti's `custom-generator` ?
> 
> If into canary, I think we should wait to merge this until #25 is merged, right?

i was intending to PR it into custom-generator but I fat fingered the button lol made the PR right before jetting out the door to head to work so was in a rush. Have changed the base branch to reflect this now, and later on when I'm back from work I'll be adding a description detailing some of the code decisions and current functionality etc so its not just a blank slate :)

**Comment by flybayer** [comment]
Looking good to me

**Comment by flybayer** [comment]
@lorenzorapetti I'll let you and @marcoseoane work out when this should be merged into your branch (there's currently a couple merge conflicts)

**Comment by marcoseoane** [comment]
> @lorenzorapetti I'll let you and @marcoseoane work out when this should be merged into your branch (there's currently a couple merge conflicts)

i've resolved the conflicts, one was a small difference in a line were @lorenzorapetti was using optional chaining + the other was using ensureDir vs mkdirSync of which ensureDir is the superior option.

**Comment by quirk0o** [comment]
did you consider using snapshot tests to test these generators? :)

**Comment by ryardley** [comment]
Looks good. I am wondering are we planning on generating into `/app`? or is that going to be `context` now.

**Comment by flybayer** [comment]
@ryardley I was definitely thinking to generate into app

**Comment by flybayer** [comment]
@all-contributors add @marcoseoane for code

**Comment by flybayer** [comment]
@marcoseoane most of this PR is now obsolete with the new architecture. Do you want to close this and then you or someone else can create a new one?

Either way, we should create a new issue to define what exactly the generate command will do and how it works.

**Comment by marcoseoane** [comment]
@flybayer thought as much! Have been laying low in these crazy times but have noticed massive progress taking place in Slack hence I haven't touched this branch with any further updates lol. Let's tie down some new requirements and I'll be happy to start rewriting something that fits our new architechture

**Comment by flybayer** [comment]
Closing in favor of #187

**Pull request closed without merging**
