### PR TITLE
Fix `blitz console` not working in vanilla JS projects

### PR DESCRIPTION
**Pull request by Flavyoo**
Closes: #461 

This continues work from https://github.com/blitz-js/blitz/pull/557

### What are the changes and their implications?

- Added `esm` dependency.
- Changed `require` to required function provided by `esm` dependency. I don't know the internals of `esm` but of course it may be slower to load the code into the console as it needs an extra step (but no other solution I would say 🤷‍♂️). 

### Breaking change: no

### CODE REVIEW

**Comment by Flavyoo** [comment]
@flybayer I have done the following validation.

1. Created a new app with a fresh installation of blitz and verified that I am able to access the `db` object and load data from the database.
2. Updated this branch and ran the plain-js example and was also able to load the `db` object.

For both cases, the running app errors out when going to `/projects` in the URL with the error `Cannot read property 'findMany' of undefined.` I thought this issue was only in the blitz console but it looks like it is in the running apps also. I believe this is the issue you were mentioning previously.

**Comment by flybayer** [comment]
@Flavyoo ok very good. Did you run `blitz generate all projects name` and `blitz db migrate` before going to `/projects`?

Also, did you check if you can use queries/mutations in the console both ways? (This was the issue I remember)

**Comment by Flavyoo** [comment]
Yes I did. I followed the steps in the index page.

However, I ran the steps again and it is working for the blitz app I created.

I validated these ways:

New App with Fresh Blitz Installation:
- db.project.findMany().then(console.log) # works
- await db.project.findMany() # works

Plain Js App from this PR:
- db.project.findMany().then(console.log) # works
- await db.project.findMany() #works

**Comment by flybayer** [comment]
Ok good, so what I meant by testing queries/mutations is does this work?

```
// have to provide a mock ctx object as second param
await getProjects({}, {authorize: ()=>{}})
```

**Comment by Flavyoo** [comment]
I see, I will try that

**Comment by Flavyoo** [comment]
@flybayer Looks like I can't run `await getProjects({}, {authorize: ()=>{}})`. 
I get this error:

```
Uncaught ReferenceError: getProjects is not defined
    at REPL1:1:16
```

**Comment by flybayer** [comment]
@Flavyoo ok, so query/mutation loading has been broken in published blitz for awhile: https://github.com/blitz-js/blitz/issues/1233

It was working in our repo until this PR though. So this PR actually makes it break in our mono repo same as production which is probably a good thing :)

**Pull request merged**
