### PR TITLE
`@blitzjs/installer` improvements

### PR DESCRIPTION
**Pull request by JuanM04**
## Changes

- Upgraded `@blitzjs/installer` and all recipes dependencies and handled their changes
- Blitz Config transformers
  - Added `transformBlitzConfig` transformer for easy modification of the Blitz config
  - Added `wrapBlitzConfig` to add plugins like `withBundleAnalyzer(config)`
  - `addBlitzMiddleware` now uses `transformBlitzConfig` under the hood
  - `secureheaders` and `theme-ui` now uses these transformers
- Babel transformers
  - Improved `addBabelPlugin` by preventing repetitions and allowing complex objects as options
  - Added `addBabelPreset`, that's basically `addBabelPlugin` but it looks for the "presets" key instead of "plugins"
  - `emotion` and `reflexjs` now uses `addBabelPreset`
- Changed dependencies from `latest` or `2.0.0` to `2.x`, so it installs the latest version that it was tested for and prevents breaking changes.
- Upgraded `reflexjs` recipe to v2

### Additional changes

- Upgraded other dependencies to comply with `manypkg`:
  - Next.js' `ast-types`, but it doesn't matter because it was removed in a newer version (vercel/next.js#28876) and fixed some TypeScript errors, none of the logic changed.
  - `@blitzjs/generator` packages.
  - I didn't upgraded `@mrleebo/prisma-ast` because of a bug in its types: MrLeebo/prisma-ast#3
- For some reason, when I merged `canary` into this branch, Husky formatted some files of the new i18n template

## Feature Checklist

- [x] Integration test added (see [test docs](https://blitzjs.com/docs/contributing#running-tests) if needed)
- [x] Documentation added/updated (submit PR to [blitzjs.com repo `canary` branch](https://github.com/blitz-js/blitzjs.com/tree/canary))

### CODE REVIEW

**Comment by beerose** [comment]
Hey @JuanM04! can you take a look at the lint issue?

**Comment by JuanM04** [comment]
@beerose It should be fixed

**Comment by flybayer** [comment]
Sweet! Can you also add docs for the new transformers?

**Comment by flybayer** [comment]
sorry for all the releases 😅  - npm network was failing which resulted in a failed publish and extra version bumps

**Comment by JuanM04** [comment]
no problem :sweat_smile:

**Comment by beerose** [comment]
@JuanM04 any idea what's wrong with Test Packages? They seem to be stuck

**Comment by JuanM04** [comment]
@beerose Yes, I noticed that. It works locally for me, so I was waiting until the workflow times out to check the new logs

**Comment by JuanM04** [comment]
It turned out the `blitz install` command was infinitely waiting for user input, that's why the tests timed out. So, I commented the test. I'll open a PR later that fixes that

**Pull request merged**
