### PR TITLE
Change `db/index.ts` in new app template to use `globalThis` instead of `global`

### PR DESCRIPTION
**Pull request by kripod**
### What are the changes and their implications?

While Node.js has a non-standard [`global`](https://nodejs.org/api/globals.html#globals_global) namespace object, version [12.4 introduced support](https://node.green/#ES2020-features-globalThis) for the standard [`globalThis`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/globalThis) object. [Blitz requires Node.js >=12](https://blitzjs.com/docs/getting-started#set-up-your-computer), so the change could be made without losing backwards compatibility.

### Checklist

- [ ] Tests added for changes – _N/A_
- [ ] PR submitted to [blitzjs.com](https://github.com/blitz-js/blitzjs.com) for any user facing changes – _N/A_

### CODE REVIEW

**Comment by merelinguist** [comment]
Thanks again @kripod! Could you have a look at the lint errors?

**Comment by kripod** [comment]
Sure! It turns out that only ESLint >=7 supports [`globalThis`](https://github.com/eslint/eslint/issues/12670#issuecomment-638754674), with the built-in ES2020 parser. As a workaround, please consider adding [the following code](https://github.com/eslint/eslint/issues/11553#issuecomment-476570950) to the ESLint config:

```json
{
  "globals": {
    "globalThis": false, // Read-only
  }
}
```

**Comment by flybayer** [comment]
Hey thanks for the PR @kripod!! 

I just did some digging and `eslint-config-react-app` just added support for eslint v7 relatively recently. So that means we can upgrade everything to v7 and then switch to globalThis.

[I opened an issue for upgrade eslint](https://github.com/blitz-js/blitz/issues/821). You're welcome to take that or let someone else. Once that issue is finished, then we can merge this.

**However, for this PR you also need to change** `global` to `globalThis` in all the other examples in the repo and [in the new app template](https://github.com/blitz-js/blitz/blob/canary/packages/generator/templates/app/db/index.ts)

**Comment by kripod** [comment]
Thanks for getting back to me!

Unfortunately, I’m not quite sure whether I’ll have time to do all of this.

**Comment by merelinguist** [comment]
@kripod No worries, I’ve finished up the rest for you. All that remains is for #821 to be closed, and then this can be merged.

**Comment by kripod** [comment]
@merelinguist Wonderful, thank you! 🙌

**Comment by flybayer** [comment]
Hey @kripod! We finally upgrade to eslint v7! So now we have one final issue it seems. Apparently we also have to add `es2020` as the eslint environment. This needs added to the example apps and to the new app template eslint config file.

**Comment by kripod** [comment]
Wonderful, thank you! Unfortunately, I’m currently busy with a company projects, so I may not have time to complete the task…

**Comment by flybayer** [comment]
Ok no problem!

**Comment by wKovacs64** [comment]
Not sure what the implications are (if any) of enabling `es2020` in the TS projects, but I added it to the app template and all examples.

**Comment by flybayer** [comment]
Perfect, thanks @kripod and @wKovacs64!!

@all-contributors add @kripod for code

**Pull request merged**
