### PR TITLE
fix useQuery react hooks violation

### PR DESCRIPTION
**Pull request by eliasjohansson**
### Type: refactor | fix

Closes: #334

### What are the changes and their implications? :gear:

Moved usePaginatedQuery out of its if statement to comply with rules of hooks.
Both `react-query` hooks will now be called, but the one not active will simply return null. Only the return value of blitz `useQuery` is now instead conditional based on `options.paginated`.

### Checklist

- [ ] Tests added for changes
- [ ] Any added terminal logging uses `packages/server/src/log.ts`

### Other information

I had to add 'Paginated' to the query key since both hooks cant use the same key. Does anyone know if this might cause an issue somewhere else?

### CODE REVIEW

**Comment by eliasjohansson** [comment]
We could also use `react-query` [manual](https://github.com/tannerlinsley/react-query#manual-querying) option. But that makes it not possible toggle pagination runtime. Atleast not with how its done right now. (not sure why/when you would wanna toggle it though)

**Comment by MrLeebo** [comment]
Thank you for tackling this issue!

However, I think this should just be two hooks. The "paginated" param fundamentally changes the behavior of the hook and I don't understand why a component would ever need to toggle it in the same component. We shouldn't present users with an option if we don't want them to take it because inevitably, someone will. 

I'm worried that this solution, while clever, introduces new potential issues. Anytime a method has a boolean parameter that drastically changes its behavior like this, that method is usually written better as two methods. Also, attaching 'Paginated' to the cache key is surprising and makes it possible to collide with another cache key by that name.

**Comment by eliasjohansson** [comment]
Should we close this and make seperate query hooks instead?

**Comment by flybayer** [comment]
@eliasjohansson yeah, let's switch to using separate hooks, just like react-query has

**Pull request closed without merging**
