### PR TITLE
Fix some dependency install warnings

### PR DESCRIPTION
**Pull request by enzoferey**
Closes: #229.

### What are the changes and their implications?

- Remove unneeded `@types/serialize-error` dependency => no implications, the library ships types.
- Replace `path-is-absolute` dependency (deprecated) in favour of `path.isAbsolute` => no implications, the change should be seamless.
- Remove commented (and duplicated) import => no implications, just useless code.

### Checklist

- [ ] Tests added for changes => nothing is tested over here, do we want to extract the `resolveFilepath` function and test it ? Probably not 🤔
- [x] User facing changes documented => no changes

### Other information

--

### CODE REVIEW

**Comment by enzoferey** [comment]
Looking in the [CI](https://github.com/blitz-js/blitz/pull/547/checks?check_run_id=703912946#step:4:9), it looks like the warnings are still there ?

**Comment by flybayer** [comment]
Awesome, thank you!! I'm only seeing warnings in CI for other things, not for the things you changed.

@all-contributors add @enzoferey for code

**Comment by enzoferey** [comment]
I meant first and third warning @flybayer 🤔 

Screenshot 2020-05-26 at 21 05 20

**Comment by flybayer** [comment]
I don't know why it showed up there for that the check install time task. Warnings aren't there on the ubuntu and windows runners and locally for me.

**Pull request merged**
