### PR TITLE
[RFC] Blitz Auth Session Management

### PR DESCRIPTION
**Pull request by flybayer**
Woohoo! Finally we have the RFC for session management.

The purpose of this RFC (Request for Comments) is to gather any feedback from the community.

We welcome all feedback, whether good or bad! This is your chance to ensure Blitz meets the needs of your company or project.

Also we'd like your feedback on the Blitz developer interface. This can, and probably will, be refined and improved.

### 👉 [View the Rendered RFC](https://github.com/blitz-js/blitz/blob/rfc-session/rfc-docs/03-session-management.md) 👈

---

### Todo

- [ ] How to expose the session inside `getServerSideProps`?

### CODE REVIEW

**Comment by dajinchu** [comment]
This looks amazing and I can't wait for it to be available. Will the session be available in `getServerSideProps`?

**Comment by goldo** [comment]
Hi! Thanks for the RFC. I was wondering, would passwordless be an option ? 
To me, passwordless is a great solution:
- you don't have to store passwords
- you will avoid some attackers who are looking for DBs with passwords
- you will rely on the security of your email provider, which is way more secure than what you will build, and.. it's free

I mean no database in the world is safe, if you want to to rely on something robust, without dragging attention, I think it's a good solution

**Comment by raulingg** [comment]
Pretty neat solution! 👌

**Comment by flybayer** [comment]
> This looks amazing and I can't wait for it to be available. Will the session be available in `getServerSideProps`?

Great question @dajinchu! Hadn't thought about that. We can definitely expose the session there. Just need to think about the best way to do that.

**Comment by flybayer** [comment]
> Hi! Thanks for the RFC. I was wondering, would passwordless be an option ?
> To me, passwordless is a great solution:

@goldo yes, for sure! This session management will work with any identity verification method/service, including passwordless.

**Comment by merelinguist** [comment]
This all looks really great! I love the session hook. What’s the timeline for the authorisation RFC?

**Comment by flybayer** [comment]
@merelinguist here's the latest word from @rishabhpoddar on implementation timeline, which starts now:

> Will take a couple of weeks. First to architect the solution keeping in mind future changes we have planned, and then about a week to build and test.

This will be for the essential security level without anonymous sessions. The rest will follow.

**Comment by dwightwatson** [comment]
Something I'd be curious to know more about (that I'm not sure is covered here) is whether Blitz auth solution will handle things on the database end as well - as in, provide migrations and boilerplate to register users, login users etc. - or will it just provide the session token abstraction and leave the implementation to the developer?

**Comment by flybayer** [comment]
@dwightwatson user registration/login/password reset/etc will be provided as a Blitz recipe/installer (#242). It'll scaffold out all the code into your project. So you get the benefit of not writing it from scratch, **and** you get the benefit of having total ownership over it. So you aren't locked into a certain library or anything. 

As a reference for Rails people, this will be the "devise" for Blitz apps.

**Comment by dwightwatson** [comment]
Fantastic news, appreciate the clarification on that point.

**Comment by Romstar** [comment]
@flybayer @rishabhpoddar 

I am planning to utilize a middleware for the session given that Redis is always significantly more performant than PostgreSQL.  Can we make adding a middleware for the session management intuitive?

**Comment by flybayer** [comment]
@Romstar yes for sure! I think we'll have a config similar to this so you have full control over where and how sessions are stored:

```js
const config = {
  getSession: sessionHandle => /* access persistent storage and return */,
  getAllSessionsForUser: userId => /* access persistent storage and return */,
  createSession: session => /* access persistent storage and return */,
  updateSession: session => /* access persistent storage and return */,
  deleteSession: session => /* access persistent storage and return */,
}
```

What do you think about that?

**Comment by matepapp** [comment]
Hey! 👋 

Have you thought about combining forces and integrating [`next-auth`](https://github.com/iaincollins/next-auth) into Blitz? It could be an opt-in solution, like Prisma, when we're talking about database management. I know it's pretty new, but I think it worths checking out, and it would fit into the project pretty well.

**Comment by flybayer** [comment]
@matepapp thanks for the tip! I did not know about that. Cool project!

From what I can tell our custom session management library will be even more full featured and have a lot better integration with Blitz than next-auth could.

**Pull request merged**
