### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by pgrimaud**
Hey,

This PR will fix : 

- 1 typo in `CONTRIBUTING.md`
- 1 typo in `examples/store/app/products/pages/products/index.tsx`
- 1 typo in `packages/cli/src/index.ts`
- 1 typo in `packages/cli/src/utils/load-blitz.ts`
- 1 typo in `packages/server/register/launch-editor.js`

Bye! :robot:

### CODE REVIEW

**Comment by pgrimaud** [comment]
@merelinguist 

Sure, but I can't find the typo. The first character of "blitz" without uppercase?

**Comment by merelinguist** [comment]
@pgrimaud 

1. Capitalise Blitz

2. Make the wording a little less awkward, e.g.: “Blitz is not available yet”

**Comment by pgrimaud** [comment]
@merelinguist I also updated `blitz/packages/blitz/bin/blitz` file

**Comment by merelinguist** [comment]
Thanks!

**Comment by flybayer** [comment]
@all-contributors add @pgrimaud for code

**Pull request merged**
