### PR TITLE
Import Blitz Projects

### PR DESCRIPTION
**Pull request by ditorojuan**
Closes: #619 

### What are the changes and their implications?
Adds a file browser to the blitz GUI

### Checklist

- [x] BE - Add Query to surf the user folders in search of blitz projects
- [x] Adds projects to the DB
- [x] UI - Make controls for the browser UI
- [x] UI - Render folders 
- [ ] UI - Responsiveness -- not sure if this is needed tbh(at least for mobile devices)
- [ ] Tests added for changes
- [ ] Clean the Code 😅

### Screenshots

Screen Shot 2020-06-07 at 11 27 51 PM

Screen Shot 2020-06-07 at 11 28 09 PM

Screen Shot 2020-06-07 at 11 40 55 PM

Screen Shot 2020-06-07 at 11 29 53 PM

### CODE REVIEW

**Comment by flybayer** [comment]
@ditorojuan awesome thank you! 

Is this ready to merge or are you going to finish all the checklist items before being ready? If the latter, you can convert it to a "draft PR" until everything is finished.

Also make sure to run prettier on the files :)

**Comment by merelinguist** [comment]
Nice work so far @ditorojuan!

**Comment by ditorojuan** [comment]
> @ditorojuan awesome thank you!
> 
> Is this ready to merge or are you going to finish all the checklist items before being ready? If the latter, you can convert it to a "draft PR" until everything is finished.
> 
> Also make sure to run prettier on the files :)

Oh no, it is not ready yet 😅, I'm planning to complete most of them yes. Did not know about the tag thing my bad. 

I see @merelinguist added it for me, thanks!

**Comment by ditorojuan** [comment]
@merelinguist 
Just pushed what should be the MVP for the FileBrowser(what's left to do is maybe optimization and code cleanup), I did some changes on the Project Schema so migrations should be runned for it to work correctly 

Just a quick question 😅 , Shouldn't we ignore `gui.db` and `migrations/`?

**Comment by merelinguist** [comment]
Wow nice work on this @ditorojuan! Yes, we should be ignore the db file, though not the migrations. Please feel free to delete and add to the gitignore!

**Comment by merelinguist** [comment]
Playing with this locally now, this is incredible stuff!

**Comment by merelinguist** [comment]
Could you make the default base be homedir rather than root?

**Comment by ditorojuan** [comment]
Yes it can definitely start from homedir, ill update it later today

**Pull request merged**
