### PR TITLE
Enable automatic network request cancelation for queries/mutations

### PR DESCRIPTION
**Pull request by hardfire**
Closes: https://github.com/blitz-js/blitz/issues/1055

### What are the changes and their implications?
I realized that instead of making changes in all the `use-*-query` hooks this could be handlled independently in the `executeRpcCall` . This does add a bit of complexity to `rpc.ts` but i'll take a stab to refactor it and still have to test it. 

### Checklist

- [ ] Tests added for changes
- [ ] PR submitted to [blitzjs.com](https://github.com/blitz-js/blitzjs.com) for any user facing changes

### CODE REVIEW

**Comment by flybayer** [comment]
@hardfire I marked this PR as a "draft" instead of using "WIP" in the title. So when you are done, you can click the "Ready for review" button to take it out of "draft" status.

**Comment by hardfire** [comment]
awesome! didn't know of the "draft" feature. Also, do review if the approach seems right.

**Comment by flybayer** [comment]
@hardfire ah nice. Did you confirm that that works?

Let's change this code to only use one `.then()`. Make that handler async, and use `await` inside that. This will make it cleaner.

```ts
.then(async (result) => {
  // stuff
  try {
    const json = await result.json()
    // more stuff
  } catch(err) {
    //stuff
  }
})

**Comment by hardfire** [comment]
> @hardfire ah nice. Did you confirm that that works?

Yes! tested it manually on one of the examples. 
Moved all of the then's to a single async function.

Its weird why the CI/Lint fails though.

**Review by flybayer — APPROVED** [review]

**Comment by flybayer** [comment]
Thank you!!

@all-contributors add @hardfire for code

**Pull request merged**
