### PR TITLE
Add support for `blitz.config.ts`

### PR DESCRIPTION
**Pull request by flybayer**
Closes: https://github.com/blitz-js/blitz/issues/913

### What are the changes and their implications?

Add support for `blitz.config.ts`. We use `esbuild` to bundle your blitz config file and output it at `.blitz/blitz.config.js`.

## Feature Checklist

- [x] Integration test added (see [test docs](https://blitzjs.com/docs/contributing#running-tests) if needed)
- [ ] Documentation added/updated (submit PR to [blitzjs.com repo](https://github.com/blitz-js/blitzjs.com))
- [x] Update recipe installer
- [x] Test Vercel deployment

### CODE REVIEW

**Comment by andreasasprou** [comment]
Can this be disabled by default for non `.ts` files?

esbuild does not support [features that need a type system](https://esbuild.github.io/content-types/#no-type-system), which are required for libraries like [Typegoose](https://typegoose.github.io/typegoose/).

**Comment by flybayer** [comment]
@andreasasprou so `blitz.config.js` is failing for you because `emitDecoratorMetadata` is in `tsconfig` even though `blitz.config.js` isn't importing any typescript? 🤔

**Comment by sebastianhoitz** [comment]
@flybayer after upgrading to the new `blitz.config.ts` it looks like `next/image` has problems with custom registered domains. It complains they are not added to the config. Did some mapping get lost?

**Comment by flybayer** [comment]
@sebastianhoitz hmm, that's not expected. Can you open an issue?

**Pull request merged**
