### PR TITLE
Add missing dependencies to `config` and `display` packages

### PR DESCRIPTION
**Pull request by konradkalemba**
Closes: #1556 

### What are the changes and their implications?

This PR adds missing required dependencies for `@blitzjs/config` and `@blitzjs/display` packages. Therefore fixes the problem with modules not found when installing recipes.

### Checklist

- [ ] <s>Tests added for changes</s>
- [ ] <s>PR submitted to [blitzjs.com](https://github.com/blitz-js/blitzjs.com) for any user facing changes</s>

### CODE REVIEW

**Comment by aaronshaf** [comment]
I assume this will fix `Error: Cannot find module '@blitzjs/config'`

**Comment by konradkalemba** [comment]
@aaronshaf Yes, it does fix that. 

However I'm not really sure why building packages fail during CI processes. :/ They're building correctly on my local machine.

**Comment by flybayer** [comment]
Hey @konradkalemba thank you for attempting this! In an effort to get this fixed asap, I made the PR which you must have seen. Issue was specifically with the installer package, but I see there's another issue with the next dependency. I'm going to make a PR shortly to fix that in config package with dynamic require.

**Comment by konradkalemba** [comment]
@flybayer Yeah, I saw both of your PRs. I didn't know it could be fixed like that!

**Pull request closed without merging**
