### PR TITLE
Add `page.authenticate`, `page.redirectAuthenticatedTo`, and `page.suppressFirstRenderFlicker`

### PR DESCRIPTION
**Pull request by flybayer**
### What are the changes and their implications?

This implements [the auth techniques used by Vercel](https://www.notion.so/Re-recreating-Vercel-s-static-in-app-page-skeleton-loaders-in-Next-js-1b8b589678d445e8a27a1cd9ad302a85).

- Set `page.authenticate = true` to throw `AuthenticationError` if not logged in
- Set `page.authenticate = {redirectTo: '/login'}` to redirect to login page if not logged in (automatically sets `router.query.next` to original location)
- Set `page.redirectAuthenticatedTo = '/'` to redirect logged in users (like on login/signup pages)
- Set `page.suppressFirstRenderFlicker = true` hide content on first render. This is a huge UX boost for pages where first render shows one thing but second render shows another (like useSession for example).
  - This is automatically enabled for `page.authenticate` and `page.redirectAuthenticatedTo`

### Checklist

- [ ] Changes covered by tests (tests added if needed)
- [ ] PR submitted to [blitzjs.com](https://github.com/blitz-js/blitzjs.com) for any user facing changes

### CODE REVIEW

**Comment by MrLeebo** [comment]
Now this is the kind of feature that Blitz is all about 👏 👏 

<sub>It's spelled *suppress* though.</sub>

**Comment by engelkes-finstreet** [comment]
This is awesome 🚀  I really like this change!

**Comment by flybayer** [comment]
@MrLeebo haha, good thing someone around here is good with spelling 😅

**Comment by flybayer** [comment]
I just added ability to set `page.authenticate = {redirectTo: '/login'}` to redirect to login page if not logged in (automatically sets `router.query.next` to original location)

**Pull request merged**
