### PR TITLE
feat(cli): use custom template format instead of EJS

### PR DESCRIPTION
**Pull request by aem**
### Type: Feature

Closes: https://github.com/blitz-js/blitz/issues/235

### What are the changes and their implications? :gear:

This removes our usages of the `.ejs` templating language and replaces it with a custom templating system. Since we don't actually use any templating functionality other than pure variable replacement, we can move from `mem-fs-copy`'s `copyTpl` function to the raw `copy` function which lets us supply a custom processing function. In our case, we just do global string replaces on any code that matches the `__variable__` pattern with a variable that exists in the template. 

As an extension, we had to centralize the generation logic to ensure that each generator doesn't have to re-implement this logic themselves. This _drastically_ simplifies each `Generator` subclass which now just needs to supply a template name, a subdirectory within the project where its files should be placed, and a function that will return the values to pass to the template. I was initially worried that this API would be a bit too abstract, but I've come to like the fact that creating a new generator is now more about writing up the template and less about writing generation code. There's of course an escape hatch which is just to override the `async write` function. 

### Checklist

- [ ] Tests added for changes
- [ ] Any added terminal logging uses `packages/server/src/log.ts`

### CODE REVIEW

**Comment by flybayer** [comment]
This is looking much better!!

- `.gitignore` still isn't working right (I verified I pulled your latest code)
```
CREATE    db/schema.prisma
CREATE    gitignore
CREATE    integrations/.keep
```

- Something in here is causing a significant hang between "Dependencies successfully installed." and "Your new Blitz app is ready! Next steps:" during `blitz new`

**Comment by aem** [comment]
@flybayer I'm guessing the delay is because the gitignore isn't getting copied, the CLI is probably trying to do some processing to the whole tree, some of which is now things like `node_modules` if the gitignore is malformed

**Comment by flybayer** [comment]
Ok, delay is fixed and `.gitignore` is generated, but the log for gitignore is wrong:

```
CREATE    db/schema.prisma
CREATE    gitignore
CREATE    integrations/.keep
```

Missing the dot

**Comment by aem** [comment]
@flybayer 🤦 i fixed that but had the commit stashed while resolving some conflicts. pushing it up now

**Comment by merelinguist** [comment]
Okay I might be wrong but I think @Zeko369’s recent pull broke the ability to create new projects! 

```sh
$ /Users/dylan/dev/blitz/node_modules/.bin/blitz new aem-test
You are using alpha software - if you have any problems, please open an issue here:
  https://github.com/blitz-js/blitz/issues/new/choose

You are not inside a Blitz project, so this command won't work.
You can create a new app with blitz new myapp or see help with 
 ›   Error: Not in correct folder
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by aem** [comment]
@merelinguist you're definitely correct. I'm going to open up a revert PR for that

**Comment by merelinguist** [comment]
Thanks!

**Comment by merelinguist** [comment]
Otherwise this all looks great, by the way 👍

**Comment by merelinguist** [comment]
@flybayer Looks grand to me, will let you merge.

**Pull request merged**
