### PR TITLE
Hide all the scary warning messages during `blitz new`

### PR DESCRIPTION
**Pull request by eliasjohansson**
### Type: DX improvement

Closes: #296 

### What are the changes and their implications? :gear:

`blitz new`
- Hide yarn/npm install output
- Pipe yarn/npm install output to blitz-log.log
- Show spinner while installing dependencies

### Breaking change: no

### CODE REVIEW

**Comment by ryardley** [comment]
Are we happy to write a log file every time regardless of success failure? Just wondering if for example it would make sense to have a flag configure the install log and then buffer all output before sending to blitz-error.log only if the process fails?

**Comment by flybayer** [comment]
Pending changes according to: https://github.com/blitz-js/blitz/issues/296#issuecomment-620528980

**Comment by eliasjohansson** [comment]
Alright, second version of this. Set npm logs to silent. Used the `--json` flag for yarn and then took the `step` messages and made them look like the rest of the CLI. I might be missing something, but is this closer to what we want? @aem @flybayer

**Comment by flybayer** [comment]
Yarn output is awesome!!!

image

---

Npm not so much (see below). There's two other bugs here I just opened issues for:
- Prettier error when using npm: https://github.com/blitz-js/blitz/issues/331
- Git repo not being initialized before dependency install so husky fails: https://github.com/blitz-js/blitz/issues/330

Ugh, we need those e2e tests so bad

**Let's try also using a spinner for npm and see if we get any pushback (probably won't)** We can add more fine grained status updates for npm when they add the json flag

--- 
image

**Comment by eliasjohansson** [comment]
So add back a spinner for NPM. Do we want to output the npm logs to a file instead? And im guessing we want to output any errors in console still?

**Comment by flybayer** [comment]
The UX of this is good now, thank you!

One question: if npm or yarn throws an error, will that error be printed to the console (it should be)

**Comment by eliasjohansson** [comment]
@flybayer Now all errors should be logged. Had alot of issues with actually testing this. Prisma throws the following error when installing with npm:
`Error: Either provide --schema or make sure that you are in a folder with a schema.prisma file.`
However it does not result in a failed install.

**Comment by flybayer** [comment]
Fyi I'm working right now to fully land this

**Comment by flybayer** [comment]
Sweeeet — great work @eliasjohansson!

**Pull request merged**
