### PR TITLE
Add dot option to glob

### PR DESCRIPTION
**Pull request by ryardley**
image

### What are the changes and their implications?

Added dot option to ensure `.babelrc` is copied to dev folder.

### Checklist

- [ ] Tests added for changes
- [ ] PR submitted to [blitzjs.com](https://github.com/blitz-js/blitzjs.com) for any user facing changes

### CODE REVIEW

**Comment by ryardley** [comment]
cc @merelinguist

**Comment by merelinguist** [comment]
Thank you!

**Comment by ryardley** [comment]
Does that do the trick?

**Comment by merelinguist** [comment]
Testing...

**Pull request merged**
