### PR TITLE
Install recipe automatically (`blitz install --yes`)

### PR DESCRIPTION
**Pull request by JuanM04**
### What are the changes and their implications?

It [re-adds the `blitz install` test](https://github.com/blitz-js/blitz/pull/2887#issuecomment-966735413) by adding a new flag: `--yes` or `-y`. When passed to the command, it installs the recipe automatically without need of user input (like pressing ENTER after each step). I chose `--yes` because it's widely used in many package managers like apt or dnf.

Also, the steps of the recipe builder were split into ones with `useInput` and ones without it - the code turned out kinda ugly, but it works. This prevents the following error (that was _also_ making the tests idle):

```
Error: Raw mode is not supported on the current process.stdin, which Ink uses as input stream by default.
Read about how to prevent this error on https://github.com/vadimdemedes/ink/#israwmodesupported
```

## Feature Checklist

- [x] Integration test added (see [test docs](https://blitzjs.com/docs/contributing#running-tests) if needed)
- [x] Documentation added/updated (submit PR to [blitzjs.com repo `canary` branch](https://github.com/blitz-js/blitzjs.com/tree/canary))

### CODE REVIEW

**Comment by JuanM04** [comment]
After a lot of time trying to discover why the test never exists even after these changes, I think I found it. I believe it's a Jest error: facebook/jest#11470

When you run Jest with `--detectOpenHandles` it throws that there is a `DNSCHANNEL` that prevents Jest from exiting. It was fixed in v27.0.2.

**Review by beerose — CHANGES_REQUESTED** [review]
Noticed the following error when installing a recipe (both with and without the `--yes` flag):

```
  ERROR  Text string "" must be rendered inside <Text> component

 /Users/aleksandra/blitz/node_modules/ink/src/reconciler.ts:129:10

 - createTextInstance (/Users/aleksandra/blitz/node_modules/ink/src/reconciler.ts:129:10)
 -completeWor (/Users/aleksandra/blitz/node_modules/react-reconciler/cjs/react-reconciler.de
             velopment.js:11201:40)
 -completeUnitOfW (/Users/aleksandra/blitz/node_modules/react-reconciler/cjs/react-reconcile
  rk             r.development.js:15373:16)
 -performUnitOfW (/Users/aleksandra/blitz/node_modules/react-reconciler/cjs/react-reconciler
  rk            .development.js:15348:5)
 -workLoopSyn (/Users/aleksandra/blitz/node_modules/react-reconciler/cjs/react-reconciler.de
             velopment.js:15268:5)
 -renderRootSy (/Users/aleksandra/blitz/node_modules/react-reconciler/cjs/react-reconciler.d
  c           evelopment.js:15231:7)
 -performSyncWorkOn (/Users/aleksandra/blitz/node_modules/react-reconciler/cjs/react-reconci
  oot              ler.development.js:14821:18)
 - (/Users/aleksandra/blitz/node_modules/react-reconciler/cjs/react-reconciler.development.j
  s:2546:26)
 -unstable_runWithPrio (/Users/aleksandra/blitz/node_modules/scheduler/cjs/scheduler.develop
  ity                 ment.js:468:12)
 -runWithPriori (/Users/aleksandra/blitz/node_modules/react-reconciler/cjs/react-reconciler.
  y            development.js:2495:10)
✕ Error: Text string "" must be rendered inside <Text> component
```

**Comment by JuanM04** [comment]
> Noticed the following error when installing a recipe (both with and without the `--yes` flag)

@beerose it should be fixed, could you try again?

**Comment by beerose** [comment]
> > Noticed the following error when installing a recipe (both with and without the `--yes` flag)
> 
> @beerose it should be fixed, could you try again?

Yep, works fine now!

**Review by beerose — APPROVED** [review]

**Pull request merged**
