### PR TITLE
Adds --port and --hostname to blitz start and dev commands

### PR DESCRIPTION
**Pull request by ivandevp**
### Type: feature 

Closes: #301 

### What are the changes and their implications? :gear:

- Add `--port` and `--hostname` flags to start and dev commands
- Move `-p` alias to `--port` instead of `--production`
- Add `detect-port` library to get available port on hostname and pass it to nextjs

### Checklist

- [X] Tests added for changes
- [ ] Any added terminal logging uses `packages/server/src/log.ts`

### Breaking change: yes 

Now projects running the build with `-p` for _production_ won't longer work since that alias will refer to `--port`.

### CODE REVIEW

**Comment by ivandevp** [comment]
Is the error in Github Actions related with `react-query` normal? Is it happening because of any dependency update?

**Comment by flybayer** [comment]
Looks good to me @ivandevp! But yeah, looks like the react-query update has a breaking type change. Can you back out that update? Then we should be good to go as long as @ryardley approves the server related changes

**Comment by flybayer** [comment]
Just change react-query to be pinned at `1.2.9`

**Comment by ivandevp** [comment]
@flybayer @ryardley I've updated the PR with a fixed version of `react-query`. Now it doesn't break the build.

**Comment by ivandevp** [comment]
May I ask to be added to all-contributors? 😊

**Comment by aem** [comment]
absolutely!

@all-contributors add @ivandevp for code

**Pull request merged**
