### PR TITLE
Add ability to set blitz logging type to `json`

### PR DESCRIPTION
**Pull request by lovethebomb**
Closes: #2876

### What are the changes and their implications?

Add a `LogType` to `next/server/config-shared` and pass the optional `type` from config to `baseLogger`

## Bug Checklist

- [ ] Integration test added (see [test docs](https://blitzjs.com/docs/contributing#running-tests) if needed)

## Feature Checklist

- [ ] Integration test added (see [test docs](https://blitzjs.com/docs/contributing#running-tests) if needed)
- [ ] Documentation added/updated (submit PR to [blitzjs.com repo `canary` branch](https://github.com/blitz-js/blitzjs.com/tree/canary))

### CODE REVIEW

**Comment by flybayer** [comment]
Sweet! I think this is the best way to address chalk issue:

In [our rpc middleware](https://github.com/blitz-js/blitz/blob/canary/nextjs/packages/next/server/api-utils.ts#L169-L245), instantiate a new chalk object that disables colors if the logger is type json.
```ts
import {Chalk} from 'chalk';

const customChalk = new Chalk({level: baseLogger._parentOrDefaultSettings.type === 'json' ? 0 : chalk.level});
```

**Comment by lovethebomb** [comment]
In ce7b001 I had to refer to the syntax of the older version of `chalk`, 2.4.2, but I believe it is still correct.

**Comment by lovethebomb** [comment]
@beerose @flybayer Is there anything I can do prevent the tests from failing due to whats seems to be an outdated `browserlists` db?

**Comment by flybayer** [comment]
@lovethebomb, that error was already fixed on canary, so just updating the branched fixed it.

Looks good! Final step is for you to submit a PR to the docs repo to document the new option

**Comment by alanlanglois** [comment]
@flybayer @beerose any idea when we can except a release including this PR?

**Comment by beerose** [comment]
> @flybayer @beerose any idea when we can except a release including this PR?

Should be today!

**Pull request merged**
