### PR TITLE
Add e2e tests to auth example

### PR DESCRIPTION
**Pull request by rubenmoya**
Closes: https://github.com/blitz-js/blitz/issues/754

### What are the changes and their implications?

This PR adds E2E tests with Cypress to the auth example.

- Added Cypress following the store example
- Renamed `Error` to `ErrorComponent` to fix an error introduced in https://github.com/blitz-js/blitz/pull/808

### Checklist

- [x] Tests added for changes
- [ ] PR submitted to [blitzjs.com](https://github.com/blitz-js/blitzjs.com) for any user facing changes

I'm not sure about how to organize the tests with Cypress so feedback is really welcome.

### CODE REVIEW

**Comment by rubenmoya** [comment]
It failed becuase `Couldn't start server on port 3099 because it's already in use`, not sure why

**Comment by flybayer** [comment]
@rubenmoya thank you so much! I'm so sorry for the long delay replying here. I was traveling from Thailand to the US this week :) 

That error is because the example tests are running in parallel, so both store example and auth example tests run at the same time. 

The solution is to use a different port for the auth example.

**Comment by flybayer** [comment]
Awesome @rubenmoya, thank you so much!!!

@all-contributors add @rubenmoya for test

**Comment by rubenmoya** [comment]
Thank you for fixing the tests!

**Comment by flybayer** [comment]
You're welcome!

**Pull request merged**
