### PR TITLE
Add `blitz generate query` to generate a single query

### PR DESCRIPTION
**Pull request by aem**
### What are the changes and their implications?

From @flybayer's stream with Kitze. A single query generator that generates a generic query function is a nice-to-have QOL improvement. Pretty easy to get setup with the generator framework! I'll do something similar for pages/mutations later today.

Docs: https://github.com/blitz-js/blitzjs.com/pull/132

### CODE REVIEW

**Comment by Skn0tt** [comment]
You're first 😂 I've also been watching the stream and started working on it: [add-singular-generators](https://github.com/blitz-js/blitz/tree/add-singular-generators)

**Comment by flybayer** [comment]
Awesome, thanks! :)

Can you also open a PR to add this to the docs?

**Comment by aem** [comment]
https://github.com/blitz-js/blitzjs.com/pull/132

**Comment by flybayer** [comment]
Woohoo! :)

**Pull request merged**
