### PR TITLE
Change store example to use single query for both pagination and infinite loading

### PR DESCRIPTION
**Pull request by scisteffan**
Closes: #858

### What are the changes and their implications?

Updated the paginated product list in the store example to calculate hasMore logic on the server, to fix a bug when the Next button would be incorrectly disabled.

I added strick null check = true to tsconfig.json since this is enabled by default on new blitz projects, and fixed compilation errors.

### Checklist

- [ ] Tests added for changes
- [ ] PR submitted to [blitzjs.com](https://github.com/blitz-js/blitzjs.com) for any user facing changes

### CODE REVIEW

**Comment by flybayer** [comment]
Great work @scisteffan!!

After seeing all this, I think we should consolidate `getProducts`, `getProductsPaginated`, and `getProductsInfinite` all into a single `getProducts`. 

Are you up for making that change?

And then as a separate task, I think we should update the default query generator to match this because everyone is going to need pagination of some sort.

**Comment by flybayer** [comment]
@all-contributors add @scisteffan for code,doc,financial

**Comment by flybayer** [comment]
@all-contributors add @scisteffan for code, doc, financial

**Comment by scisteffan** [comment]
Yep, happy to take this on board!

**Comment by scisteffan** [comment]
There's an issue when using the same query for both the paginated and infinite listings. The results of the query are cached. In the case of usePaginatedQuery, the result is an object type, whereas useInfiniteQuery it's an array. So when navigating between the two using client side navigation, the cached value is used which is of the wrong type.

Do you have any suggestions on how to fix this?

**Comment by flybayer** [comment]
Hmmm that's weird. I'll look into that.

**Comment by flybayer** [comment]
@scisteffan I found the bug! Fixed in #963 

Again thanks for your work on this!!

**Pull request merged**
