### PR TITLE
Set default generator context to 'modules' (#1183)

### PR DESCRIPTION
**Pull request by svobik7**
### What are the changes and their implications?

Added new initial context to cli generator to keep all "entity" related code in `app/modules` folder. This was initialy discussed here https://github.com/blitz-js/blitz/discussions/1183#discussioncomment-86823

### Checklist

- [x] Tests added for changes
- [x] PR submitted to [blitzjs.com](https://github.com/blitz-js/blitzjs.com) for any user facing changes

### CODE REVIEW

**Comment by flybayer** [comment]
Thanks @svobik7! Can you also go through your docs and update any files paths used there? I know for sure the Tutorial needs updated. Also the `blitz generate` doc examples and should add that modules is the default context

**Comment by svobik7** [comment]
@flybayer sure, I will update the docs.

**Comment by svobik7** [comment]
@flybayer I updated all related code in blitz packages: 
- examples folder structure
- blitz new templates
- docs and comments.

I also created PR for blitzjs.com docs https://github.com/blitz-js/blitzjs.com/pull/213

**Comment by svobik7** [comment]
PR Refactor update: 

- `--context` flag's default value is undefined again
- `--root` flag added to specify generator base path with default value = `modules`

**Comment by svobik7** [comment]
Rejected for now - https://github.com/blitz-js/blitz/discussions/1183#discussioncomment-96602

**Pull request closed without merging**
