### PR TITLE
Remove error stack from console output on testing

### PR DESCRIPTION
**Pull request by AkifumiSato**
Closes: ??

### What are the changes and their implications?
When I ran the test on `packages / core`, I got an error stack and it was confusing, so I suggest not to output this when testing.

```sh
$ cd packages/core
$ yarn test

...
 PASS  src/secure-proxy-middleware.test.ts

 Error  test
error stack:
• middleware.test.ts:154 middleware
    src/middleware.test.ts:154:35

• middleware.ts:127 dispatch
    src/middleware.ts:127:40

• middleware.ts:135 <anonymous>
    src/middleware.ts:135:16

• middleware.ts:50 <anonymous>
    src/middleware.ts:50:42

• tslib.js:139 step
    node_modules/tslib/tslib.js:139:27

• tslib.js:120 <anonymous>
    node_modules/tslib/tslib.js:120:57

• tslib.js:113 <anonymous>
    node_modules/tslib/tslib.js:113:75

• tslib.js:109 __awaiter
    node_modules/tslib/tslib.js:109:16

• middleware.ts:28 handleRequestWithMiddleware
    src/middleware.ts:28:20

• middleware.test.ts:224 <anonymous>
    src/middleware.test.ts:224:71

• tslib.js:139 step
    node_modules/tslib/tslib.js:139:27

• tslib.js:120 <anonymous>
    node_modules/tslib/tslib.js:120:57

• tslib.js:113 <anonymous>
    node_modules/tslib/tslib.js:113:75

• tslib.js:109 __awaiter
    node_modules/tslib/tslib.js:109:16

• middleware.test.ts:218 apiEndpoint
    src/middleware.test.ts:218:72

• api-utils.ts:86 apiResolver
    node_modules/next/next-server/server/api-utils.ts:86:11

code frame:
> 149 | undefined
                                          ^
 ERROR 4Error while processing the request 

 Error  test
error stack:
• middleware.test.ts:187 middleware
    src/middleware.test.ts:187:41

• middleware.ts:127 dispatch
    src/middleware.ts:127:40

• middleware.ts:135 <anonymous>
src/middleware.ts:135:16

• middleware.ts:50 <anonymous>
    src/middleware.ts:50:42

• tslib.js:139 step
    node_modules/tslib/tslib.js:139:27

• tslib.js:120 <anonymous>
    node_modules/tslib/tslib.js:120:57

• tslib.js:113 <anonymous>
    node_modules/tslib/tslib.js:113:75

• tslib.js:109 __awaiter
    node_modules/tslib/tslib.js:109:16

28 handleRequestWithMiddleware
    src/middleware.ts:28:20

• middleware.test.ts:224 <anonymous>
    src/middleware.test.ts:224:71

• tslib.js:139 step
    node_modules/tslib/tslib.js:139:27

• tslib.js:120 <anonymous>
    node_modules/tslib/tslib.js:120:57

• tslib.js:113 <anonymous>
    node_modules/tslib/tslib.js:113:75

• tslib.js:109 __awaiter
    node_modules/tslib/tslib.js:109:16

• middleware.test.ts:218 apiEndpoint
    src/middleware.test.ts:218:72

:86 apiResolver
    node_modules/next/next-server/server/api-utils.ts:86:11

code frame:
> 182 | undefined
                                                ^
 PASS  src/middleware.test.ts (7.023s)
...
```

### Checklist

- [ ] Tests added for changes
- [ ] PR submitted to [blitzjs.com](https://github.com/blitz-js/blitzjs.com) for any user facing changes

### CODE REVIEW

**Review by flybayer — CHANGES_REQUESTED** [review]
Hey @AkifumiSato! Yeah this is a good idea. However we should still log the error in tests to see what is happening, but we can remove the stack trace. I think you can do this with the `exposeStackTrace` for the logger. See the [tslog docs](https://github.com/fullstack-build/tslog) for more details.

**Comment by AkifumiSato** [comment]
> I think you can do this with the exposeStackTrace for the logger. See the tslog docs for more details.

@flybayer Thank you for the advice!
I'd like to set `exposeErrorCodeFrame` & `exposeStackTrace` to false. Is it in line with your wishes?

https://github.com/blitz-js/blitz/blob/canary/packages/core/src/middleware.ts#L81
```ts
// before
baseLogger.prettyError(error)

// after
baseLogger.prettyError(error, true, false, false)
```

log
```sh
 PASS  src/utils/tokens.test.ts
 PASS  src/invoke.test.ts
22:05:36.930.000         INFO   getTest() Starting with input: test 
22:05:36.935.000         INFO   getTest() Finished in 2ms 
22:05:36.946.000         INFO   getTest() Starting with input: test 
22:05:36.948.000         INFO   getTest() Finished in 1ms 
22:05:36.953.000         INFO   getTest() Starting with input: test 
22:05:36.955.000         INFO   getTest() Finished in 1ms 
 ERROR 7Error while processing the request 
 PASS  test/use-query.test.tsx
 PASS  test/react-query-utils.test.ts
 PASS  test/rpc.test.ts
 PASS  test/use-params.test.ts
 PASS  test/use-mutation.test.tsx
 PASS  src/public-data-store.test.ts
 PASS  src/secure-proxy-middleware.test.ts

 ERROR 0Error while processing the request 

 PASS  src/middleware.test.ts (6.053s)
```

**Comment by flybayer** [comment]
@AkifumiSato yeah, looks good!

**Comment by AkifumiSato** [comment]
All files has been fixed.

**Comment by flybayer** [comment]
@AkifumiSato looks like you accidentally removed some of your new code? Right now the PR code removes the stack trace all the time, not just during testing.

**Comment by AkifumiSato** [comment]
@flybayer sorry, that's right.
I fixed it again.

**Comment by flybayer** [comment]
Yay, thank you!!

@all-contributors add @AkifumiSato for code

**Pull request merged**
