### PR TITLE
Throw error if two pages have the same name (important for `Routes` to be accurate)

### PR DESCRIPTION
**Pull request by ravindranrahul**
Closes: #2558 

## Bug Checklist

- [ ] Integration test added (see [test docs](https://blitzjs.com/docs/contributing#running-tests) if needed)

## Feature Checklist

- [ ] Integration test added (see [test docs](https://blitzjs.com/docs/contributing#running-tests) if needed)
- [ ] Documentation added/updated (submit PR to [blitzjs.com repo](https://github.com/blitz-js/blitzjs.com))

### CODE REVIEW

**Comment by flybayer** [comment]
@ravindranrahul thanks!

Re: https://github.com/blitz-js/blitz/issues/2558#issuecomment-888381821

Did you try throwing an error instead of `console.error`?

Also we should make the error message as helpful as possible. Ideally something like 
```
The page component is named "Page" on both the /home and /users routes. The page component must have a unique name, so change the component name on one of those routes
```

**Comment by ravindranrahul** [comment]
@flybayer thanks!

I have slightly modified the error message so that it can handle conflict on more than 2 routes.

```
The page component is named "Page" for the routes "/home", "/users". 
Page components must have unique names across all routes. Please change the component name to avoid any route conflicts.
```

**Comment by ravindranrahul** [comment]
@flybayer thanks for the instructions. I have updated the code. Please find the error message shown on `examples/auth` app (which already has a conflicting page component)

Screenshot from 2021-08-04 20-24-35

**Comment by flybayer** [comment]
Awesome, looks good! Now you just need to fix the example app so CI passes

**Comment by ravindranrahul** [comment]
@flybayer Done. Thanks, let me know if I need to do anything else.

**Comment by flybayer** [comment]
@ravindranrahul awesome. Looks like some of the integration tests are failing.


```
/home/runner/work/blitz/blitz/test/integration/auth
Running command "blitz dev" 
- Compiling
(node:3351) UnhandledPromiseRejectionWarning: Error: The page component is named "Page" on both the /authenticated-query and /gssp-setpublicdata routes. The page component must have a unique name across all routes, so change the component name on one of those routes to avoid conflict.
```

You can see instructions for running integration tests locally here: https://blitzjs.com/docs/contributing#running-tests

**Comment by ravindranrahul** [comment]
@flybayer I have fixed integration tests and it now passes locally. 

Screenshot from 2021-08-06 13-57-20

**Comment by ravindranrahul** [comment]
@flybayer exactly 1 CI check is failing. I looked at the logs, but I don't understand whats going on. I'll be happy to work with you to clear this.

**Comment by flybayer** [comment]
@ravindranrahul that failure was a fluke. Thank you for your work on this !!

**Pull request merged**
