### PR TITLE
(recipe) Update tailwind recipe to v2

### PR DESCRIPTION
**Pull request by Mzaien**
Followed the instructions but it needs testing

Closes: #1484

### What are the changes and their implications?
changed tailwind version number to 2
### Checklist

- [ ] Tests added for changes
- [ ] PR submitted to [blitzjs.com](https://github.com/blitz-js/blitzjs.com) for any user facing changes

### CODE REVIEW

**Comment by Skn0tt** [comment]
Tailwind v2 comes with the new `darkMode` option which I think we should also add to our template:
```js
darkMode: false, // or 'media' or 'class'
```

Also, when I tried out Tailwind v2 a couple of minutes ago, it failed because of a version of PostCSS that's too old - maybe also take a look at that.

**Review by flybayer — CHANGES_REQUESTED** [review]
Thanks!

There's some more changes that are needed as shown here: https://github.com/vercel/next.js/pull/19278/files

- Remove `postcss-present-env` and add the new required deps
- Update the postcss config template
- Remove the `future` key from tailwind config

**Comment by pbteja1998** [comment]
> Thanks!
> 
> There's some more changes that are needed as shown here: https://github.com/vercel/next.js/pull/19278/files
> 
> * Remove `postcss-present-env` and add the new required deps
> * Update the postcss config template
> * Remove the `future` key from tailwind config

@flybayer I don't think postcss-preset-env needs to be removed. Checkout the default postcss config that comes with Next.js [here](https://nextjs.org/docs/advanced-features/customizing-postcss-config#customizing-plugins). It already has `autoprefixer` in it. We just have to add `tailwindcss` to [this config](https://nextjs.org/docs/advanced-features/customizing-postcss-config#customizing-plugins) and also add `postcss 8` as a dev dependency.

We also no longer need to have a separate stylesheet. We can just import from `tailwindcss/tailwind.css`. I added all these in a separate PR(#1490) a while back. I did not see this PR then. I already tested the recipe I added in that PR too. So that config works. 

And another thing is that all of these can be devDependencies.

**Comment by Mzaien** [comment]
Thanks to @pbteja1998  you helped me a lot i'm a beginner in this field  And also thanks for @flybayer and @Skn0tt

**Comment by flybayer** [comment]
@Mzaien sorry for the review delay here!

The [Next.js Tailwind v2 update](https://github.com/vercel/next.js/pull/19278/files) is merged, so let's follow that.

- [ ] Remove `postcss-flexbugs-fixes`
- [ ] Remove `postcss-preset-env`
- [ ] Add `autoprefixer` dependency
- [ ] Change all dependencies to use a major version number like `"2"` instead of `"latest"` to prevent breaking change issues when major version changes
- [ ] Keep `app/styles/index.css` but remove `button.css`. 
  - @pbteja1998 you are right it's not needed, but it's very likely any app using tailwind will have some global styles to add. Having it there makes this easier. In general with Blitz we default to include the files you're likely to use vs the minimum possible.
- [ ] Change `postcss.config.js` to have this content as prescribed by the tailwind docs:
```js
// postcss.config.js
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  }
}
```

**Review by flybayer — APPROVED** [review]

**Comment by flybayer** [comment]
Awesome, thank you!!

@all-contributors add @Mzaien for code

**Pull request merged**
